WITH params AS (
    -- Período de análise consistente, usando TRUNC para comparar apenas dias.
    SELECT
        TRUNC(ADD_MONTHS(SYSDATE, -6), 'MM') AS dh_inicio,
        TRUNC(SYSDATE) AS dh_fim
    FROM DUAL
),
-- Bloco 1: Consultas Ambulatoriais (Lógica Mantida)
cte_consultas_ambulatoriais AS (
    SELECT 'CONSULTA' AS ORIGEM_QUERY,
        CASE 
            WHEN A.CD_ESPECIALID IN (77,1,55,54,3,62,2,57,65) THEN 'CONSULTA MULTI'
            WHEN A.CD_ESPECIALID IN (7,6,93,9,14,11,82,15,51,44,28,27,34,33,19,26,63,21,37,46,23) THEN 'CONSULTA MÉDICA'
            ELSE 'OUTRA CONSULTA' 
        END AS TIPO_CLASSIFICACAO,
        'P' AS FLAG_ABSENTEISMO, 
        A.CD_ATENDIMENTO, 
        A.CD_PACIENTE, 
        A.HR_ATENDIMENTO AS DATA_EVENTO,
        E.DS_ESPECIALID, 
        S.NM_SETOR, 
        NULL AS DS_PROCEDIMENTO,
        NULL AS CD_PROCEDIMENTO_SIA
    FROM DBAMV.ATENDIME A
        LEFT JOIN DBAMV.ESPECIALID E ON A.CD_ESPECIALID = E.CD_ESPECIALID
        LEFT JOIN DBAMV.ORI_ATE OA ON A.CD_ORI_ATE = OA.CD_ORI_ATE
        LEFT JOIN DBAMV.SETOR S ON OA.CD_SETOR = S.CD_SETOR
    WHERE A.CD_MULTI_EMPRESA = 40
      AND A.TP_ATENDIMENTO = 'A'
      AND A.CD_ORI_ATE = 1426
      AND TRUNC(A.HR_ATENDIMENTO) BETWEEN (SELECT dh_inicio FROM params) AND (SELECT dh_fim FROM params)
),
-- Bloco 2: Procedimentos da Prescrição (Lógica Mantida + Coluna Adicional)
cte_procedimentos_prescricao AS (
    SELECT 'PROCEDIMENTO' AS ORIGEM_QUERY, 
           'PROCEDimento_AMBULATORIAL' AS TIPO_CLASSIFICACAO, 
           'P' AS FLAG_ABSENTEISMO, 
           A.CD_ATENDIMENTO, 
           A.CD_PACIENTE, 
           PRE_MED.DH_CRIACAO AS DATA_EVENTO, 
           ESP.DS_ESPECIALID, 
           S.NM_SETOR, 
           TIP.DS_TIP_PRESC AS DS_PROCEDIMENTO,
           TIP.CD_PROCEDIMENTO_SIA
    FROM DBAMV.PRE_MED PRE_MED
        INNER JOIN DBAMV.ATENDIME A ON PRE_MED.CD_ATENDIMENTO = A.CD_ATENDIMENTO
        INNER JOIN DBAMV.ITPRE_MED ITP ON PRE_MED.CD_PRE_MED = ITP.CD_PRE_MED
        INNER JOIN DBAMV.TIP_PRESC TIP ON ITP.CD_TIP_PRESC = TIP.CD_TIP_PRESC
        INNER JOIN DBAMV.PRESTADOR PRES ON PRE_MED.CD_PRESTADOR = PRES.CD_PRESTADOR
        INNER JOIN DBAMV.ESP_MED EM ON PRES.CD_PRESTADOR = EM.CD_PRESTADOR AND EM.SN_ESPECIAL_PRINCIPAL = 'S'
        INNER JOIN DBAMV.ESPECIALID ESP ON EM.CD_ESPECIALID = ESP.CD_ESPECIALID
        LEFT JOIN DBAMV.ORI_ATE OA ON A.CD_ORI_ATE = OA.CD_ORI_ATE
        LEFT JOIN DBAMV.SETOR S ON OA.CD_SETOR = S.CD_SETOR
    WHERE A.CD_MULTI_EMPRESA = 40
      AND A.TP_ATENDIMENTO = 'A'
      AND TIP.SN_ATIVO = 'S'
      AND TRUNC(PRE_MED.DH_CRIACAO) BETWEEN (SELECT dh_inicio FROM params) AND (SELECT dh_fim FROM params)
      AND (UPPER(TRIM(TIP.DS_TIP_PRESC)) LIKE '%CURATIVO%' OR UPPER(TRIM(TIP.DS_TIP_PRESC)) LIKE '%EXERESE%' OR UPPER(TRIM(TIP.DS_TIP_PRESC)) LIKE '%CORPO ESTRA%' OR UPPER(TRIM(TIP.DS_TIP_PRESC)) LIKE '%PONTO%' OR UPPER(TRIM(TIP.DS_TIP_PRESC)) LIKE '%PINO%' OR UPPER(TRIM(TIP.DS_TIP_PRESC)) LIKE '%STEINMANN%' OR UPPER(TRIM(TIP.DS_TIP_PRESC)) LIKE '%FIXADOR EXTERNO%' OR UPPER(TRIM(TIP.DS_TIP_PRESC)) LIKE '%ENDOCÂNULA%' OR UPPER(TRIM(TIP.DS_TIP_PRESC)) LIKE '%ENDOCANULA%' OR UPPER(TRIM(TIP.DS_TIP_PRESC)) LIKE '%BUBBLE%' OR UPPER(TRIM(TIP.DS_TIP_PRESC)) LIKE '%BOTULÍNICA%' OR UPPER(TRIM(TIP.DS_TIP_PRESC)) LIKE '%BOTULINICA%' OR UPPER(TRIM(TIP.DS_TIP_PRESC)) LIKE '%SUTURA%' OR UPPER(TRIM(TIP.DS_TIP_PRESC)) LIKE '%RETIRADA DE FIO%' OR UPPER(TRIM(TIP.DS_TIP_PRESC)) LIKE '%EXCISAO DE LESAO%' OR UPPER(TRIM(TIP.DS_TIP_PRESC)) LIKE '%DEBRIDAMENTO%' OR UPPER(TRIM(TIP.DS_TIP_PRESC)) LIKE '%SEDACAO%' OR UPPER(TRIM(TIP.DS_TIP_PRESC)) LIKE '%ANESTESIA REGIONAL%')
      AND UPPER(TRIM(TIP.DS_TIP_PRESC)) NOT LIKE '%CURATIVO SIMPLES%'
),
-- Bloco 3: Atendimentos SUS (Hospital Dia) (Lógica Mantida)
cte_atendimentos_sus AS (
    SELECT 'ATENDIMENTO_SUS' AS ORIGEM_QUERY, 
           'HOSPITAL DIA' AS TIPO_CLASSIFICACAO, 
           'P' AS FLAG_ABSENTEISMO,
           A.CD_ATENDIMENTO, 
           A.CD_PACIENTE, 
           A.DT_ATENDIMENTO AS DATA_EVENTO, 
           NULL AS DS_ESPECIALID,
           S.NM_SETOR, 
           SUS.DS_PROCEDIMENTO,
           NULL AS CD_PROCEDIMENTO_SIA
    FROM DBAMV.ATENDIME A
        INNER JOIN DBAMV.PROCEDIMENTO_SUS SUS ON SUS.CD_PROCEDIMENTO = A.CD_PROCEDIMENTO
        LEFT JOIN DBAMV.ORI_ATE OA ON A.CD_ORI_ATE = OA.CD_ORI_ATE
        LEFT JOIN DBAMV.SETOR S ON OA.CD_SETOR = S.CD_SETOR
    WHERE A.CD_MULTI_EMPRESA = 40
      AND A.CD_ORI_ATE = 1422
      AND TRUNC(A.DT_ATENDIMENTO) BETWEEN (SELECT dh_inicio FROM params) AND (SELECT dh_fim FROM params)
),
-- Bloco 4: Absenteísmo (Faltas) (Lógica Original Confirmada como Correta)
cte_absenteismo AS (
    SELECT 'FALTA' AS ORIGEM_QUERY,
        CASE 
            WHEN UPPER(TP.DS_TIP_MAR) LIKE '%EXAME%' THEN 'FALTA_EXAMES'
            WHEN EM.CD_ESPECIALID IN (77,1,55,54,3,62,2,57,65) THEN 'FALTA_CONSULTA_MULTI'
            WHEN EM.CD_ESPECIALID IN (7,6,93,9,14,11,82,15,51,44,28,27,34,33,19,26,63,21,37,46,23) THEN 'FALTA_CONSULTA_MEDICA'
            ELSE 'FALTA_OUTRAS'
        END AS TIPO_CLASSIFICACAO,
        'F' AS FLAG_ABSENTEISMO, 
        NULL AS CD_ATENDIMENTO, 
        IT.CD_PACIENTE, 
        AC.DT_AGENDA AS DATA_EVENTO,
        ED.DS_ESPECIALID, 
        S.NM_SETOR, 
        NVL(TP.DS_TIP_MAR, IT.DS_OBSERVACAO) AS DS_PROCEDIMENTO,
        NULL AS CD_PROCEDIMENTO_SIA
    FROM DBAMV.IT_AGENDA_CENTRAL IT
        INNER JOIN DBAMV.AGENDA_CENTRAL AC ON IT.CD_AGENDA_CENTRAL = AC.CD_AGENDA_CENTRAL
        LEFT JOIN DBAMV.PRESTADOR P ON AC.CD_PRESTADOR = P.CD_PRESTADOR
        LEFT JOIN DBAMV.ESP_MED EM ON P.CD_PRESTADOR = EM.CD_PRESTADOR AND EM.SN_ESPECIAL_PRINCIPAL = 'S'
        LEFT JOIN DBAMV.ESPECIALID ED ON EM.CD_ESPECIALID = ED.CD_ESPECIALID
        LEFT JOIN DBAMV.TIP_MAR TP ON IT.CD_TIP_MAR = TP.CD_TIP_MAR
        LEFT JOIN DBAMV.SETOR S ON AC.CD_SETOR = S.CD_SETOR
    WHERE AC.CD_MULTI_EMPRESA = 40
      AND IT.tp_presenca_falta = 'F' 
      AND (TP.DS_TIP_MAR <> 'TRIAGEM' OR TP.DS_TIP_MAR IS NULL)
      AND TRUNC(AC.DT_AGENDA) BETWEEN (SELECT dh_inicio FROM params) AND (SELECT dh_fim FROM params)
),
-- Bloco 5: Exames SADT Realizados (Lógica Completamente Aprimorada)
cte_exames_realizados AS (
    SELECT 'EXAME_SADT' AS ORIGEM_QUERY,
        CASE 
            WHEN A.TP_ATENDIMENTO IN ('U', 'M', 'I') THEN 'EXAME_INTERNO' 
            ELSE 'EXAME_EXTERNO' 
        END AS TIPO_CLASSIFICACAO,
        'P' AS FLAG_ABSENTEISMO, 
        A.CD_ATENDIMENTO, 
        A.CD_PACIENTE, 
        CASE 
            WHEN ME.CD_MODALIDADE_EXAME = 10 THEN PED_RX.DT_PEDIDO
            ELSE ITPED_RX.DT_REALIZADO 
        END AS DATA_EVENTO,
        NULL AS DS_ESPECIALID, 
        S.NM_SETOR,
        CASE 
            WHEN ME.CD_MODALIDADE_EXAME = 3 AND EXA.DS_EXA_RX LIKE '%US DOPPLER%' THEN 'ULTRASSONOGRAFIA/DOPPLER'
            WHEN ME.CD_MODALIDADE_EXAME = 3 AND EXA.DS_EXA_RX LIKE '%ECOCARDIOGRAMA%' THEN 'ECOCARDIOGRAMA'
            WHEN ME.CD_MODALIDADE_EXAME = 3 AND EXA.DS_EXA_RX LIKE '%BRONCO%' THEN 'BRONCOSCOPIA'
            WHEN ME.CD_MODALIDADE_EXAME = 9 AND EXA.CD_EXA_RX IN (1152) THEN 'COLONOSCOPIA - ENDOSCOPIA DIGESTIVA BAIXO'
            ELSE ME.DS_MODALIDADE_EXAME 
        END AS DS_PROCEDIMENTO,
        NULL AS CD_PROCEDIMENTO_SIA
    FROM DBAMV.PED_RX
        INNER JOIN DBAMV.ATENDIME A ON PED_RX.CD_ATENDIMENTO = A.CD_ATENDIMENTO
        INNER JOIN DBAMV.ITPED_RX ON PED_RX.CD_PED_RX = ITPED_RX.CD_PED_RX
        INNER JOIN DBAMV.EXA_RX EXA ON ITPED_RX.CD_EXA_RX = EXA.CD_EXA_RX
        INNER JOIN DBAMV.SETOR S ON PED_RX.CD_SETOR = S.CD_SETOR
        INNER JOIN DBAMV.MODALIDADE_EXAME ME ON ME.CD_MODALIDADE_EXAME = EXA.CD_MODALIDADE_EXAME
    WHERE A.CD_MULTI_EMPRESA = 40
      AND (
          (ME.CD_MODALIDADE_EXAME = 10 
           AND ITPED_RX.SN_REALIZADO IN ('S', 'N')
           AND TRUNC(PED_RX.DT_PEDIDO) BETWEEN (SELECT dh_inicio FROM params) AND (SELECT dh_fim FROM params)
          )
          OR
          (ME.CD_MODALIDADE_EXAME <> 10 
           AND ITPED_RX.SN_REALIZADO = 'S'
           AND TRUNC(ITPED_RX.DT_REALIZADO) BETWEEN (SELECT dh_inicio FROM params) AND (SELECT dh_fim FROM params)
          )
      )
)

-- Bloco Final: Une TODOS OS 5 resultados com a nova coluna
SELECT CD_ATENDIMENTO, CD_PACIENTE, DATA_EVENTO, DS_ESPECIALID, NM_SETOR, DS_PROCEDIMENTO, ORIGEM_QUERY, TIPO_CLASSIFICACAO, FLAG_ABSENTEISMO, CD_PROCEDIMENTO_SIA FROM cte_consultas_ambulatoriais
UNION ALL
SELECT CD_ATENDIMENTO, CD_PACIENTE, DATA_EVENTO, DS_ESPECIALID, NM_SETOR, DS_PROCEDIMENTO, ORIGEM_QUERY, TIPO_CLASSIFICACAO, FLAG_ABSENTEISMO, CD_PROCEDIMENTO_SIA FROM cte_procedimentos_prescricao
UNION ALL
SELECT CD_ATENDIMENTO, CD_PACIENTE, DATA_EVENTO, DS_ESPECIALID, NM_SETOR, DS_PROCEDIMENTO, ORIGEM_QUERY, TIPO_CLASSIFICACAO, FLAG_ABSENTEISMO, CD_PROCEDIMENTO_SIA FROM cte_atendimentos_sus
UNION ALL
SELECT CD_ATENDIMENTO, CD_PACIENTE, DATA_EVENTO, DS_ESPECIALID, NM_SETOR, DS_PROCEDIMENTO, ORIGEM_QUERY, TIPO_CLASSIFICACAO, FLAG_ABSENTEISMO, CD_PROCEDIMENTO_SIA FROM cte_absenteismo
UNION ALL
SELECT CD_ATENDIMENTO, CD_PACIENTE, DATA_EVENTO, DS_ESPECIALID, NM_SETOR, DS_PROCEDIMENTO, ORIGEM_QUERY, TIPO_CLASSIFICACAO, FLAG_ABSENTEISMO, CD_PROCEDIMENTO_SIA FROM cte_exames_realizados