WITH params AS (
    SELECT
        TRUNC(ADD_MONTHS(SYSDATE, -10), 'MM') AS dh_inicio,
        SYSDATE AS dh_fim
    FROM DUAL
),
dados_com_duplicatas AS (
    -- Primeira Consulta: Apenas Internações
    SELECT
        A.CD_ATENDIMENTO, A.TP_ATENDIMENTO, P.CD_PACIENTE, P.NM_PACIENTE, A.HR_ATENDIMENTO, A.HR_ALTA, E.DS_ESPECIALID, UI.DS_UNID_INT,
        (NVL(A.HR_ALTA, p.DH_FIM) - A.HR_ATENDIMENTO) AS PERMANENCIA_DIAS_CALC,
        A.CD_TIPO_INTERNACAO, SC.DS_TIPO_RISCO, chamada_classif.dh_processo AS DH_CHAMADA_CLASSIF,
        classif_inicio.dh_processo  AS DH_INICIO_CLASSIF, classif_fim.dh_processo AS DH_FIM_CLASSIF,
        CID_ADM.DS_CID, PROCEDIMENTOS.CD_PROCEDIMENTO_FINAL, SUS.DS_PROCEDIMENTO, MA.DS_MOT_ALT,
        TR.SN_OBITO, P.DT_NASCIMENTO, P.TP_SEXO, SUS.CD_GRUPO_PROCEDIMENTO, A.CD_ESPECIALID,
        p.DH_FIM AS DH_FIM_PERIODO -- << CORREÇÃO: Coluna adicionada aqui
    FROM
        DBAMV.ATENDIME A
        CROSS JOIN params p
        LEFT JOIN DBAMV.PACIENTE P ON A.CD_PACIENTE = P.CD_PACIENTE
        LEFT JOIN DBAMV.MOT_ALT MA ON A.CD_MOT_ALT = MA.CD_MOT_ALT
        LEFT JOIN DBAMV.ESPECIALID E ON A.CD_ESPECIALID = E.CD_ESPECIALID
        LEFT JOIN DBAMV.TIPO_INTERNACAO TI ON A.CD_TIPO_INTERNACAO = TI.CD_TIPO_INTERNACAO
        LEFT JOIN DBAMV.LEITO L ON A.CD_LEITO = L.CD_LEITO
        LEFT JOIN DBAMV.UNID_INT UI ON UI.CD_UNID_INT = L.CD_UNID_INT
        LEFT JOIN DBAMV.TRIAGEM_ATENDIMENTO STA ON A.CD_ATENDIMENTO = STA.CD_ATENDIMENTO
        LEFT JOIN DBAMV.SACR_CLASSIFICACAO SC ON STA.CD_CLASSIFICACAO = SC.CD_CLASSIFICACAO
        LEFT JOIN DBAMV.CID CID_ADM ON A.CD_CID = CID_ADM.CD_CID
        LEFT JOIN (SELECT cd_triagem_atendimento, MIN(dh_processo) AS dh_processo FROM SACR_TEMPO_PROCESSO WHERE cd_tipo_tempo_processo = 10 GROUP BY cd_triagem_atendimento) chamada_classif ON chamada_classif.cd_triagem_atendimento = STA.cd_triagem_atendimento
        LEFT JOIN (SELECT cd_triagem_atendimento, MIN(dh_processo) AS dh_processo FROM SACR_TEMPO_PROCESSO WHERE cd_tipo_tempo_processo = 11 GROUP BY cd_triagem_atendimento) classif_inicio  ON classif_inicio.cd_triagem_atendimento = STA.cd_triagem_atendimento
        LEFT JOIN (SELECT cd_triagem_atendimento, MAX(dh_processo) AS dh_processo FROM SACR_TEMPO_PROCESSO WHERE cd_tipo_tempo_processo = 12 GROUP BY cd_triagem_atendimento) classif_fim        ON classif_fim.cd_triagem_atendimento = STA.cd_triagem_atendimento
        LEFT JOIN (
            SELECT A.CD_ATENDIMENTO, CASE WHEN AIHE.CD_PROCEDIMENTO_MUDANCA IS NOT NULL THEN AIHE.CD_PROCEDIMENTO_MUDANCA WHEN AIHE.CD_PROCEDIMENTO_MUDANCA IS NULL AND AIH.CD_PROCEDIMENTO IS NOT NULL THEN AIH.CD_PROCEDIMENTO WHEN AIH.CD_PROCEDIMENTO IS NULL AND AIHE.CD_PROCEDIMENTO_MUDANCA IS NULL AND A.CD_PROCEDIMENTO IS NOT NULL THEN A.CD_PROCEDIMENTO END AS CD_PROCEDIMENTO_FINAL
            FROM DBAMV.ATENDIME A
            LEFT JOIN DBAMV.LAUDO_AIH AIH ON AIH.CD_ATENDIMENTO = A.CD_ATENDIMENTO
            LEFT JOIN DBAMV.LAUDO_AIH_ESPECIAL AIHE ON AIHE.CD_LAUDO = AIH.CD_LAUDO
            WHERE (AIH.CD_LAUDO IN (SELECT MAX(AIH2.CD_LAUDO) FROM DBAMV.LAUDO_AIH AIH2 WHERE AIH2.CD_ATENDIMENTO = A.CD_ATENDIMENTO) OR AIH.CD_LAUDO IS NULL)
        ) PROCEDIMENTOS ON PROCEDIMENTOS.CD_ATENDIMENTO = A.CD_ATENDIMENTO
        LEFT JOIN DBAMV.PROCEDIMENTO_SUS SUS ON SUS.CD_PROCEDIMENTO = PROCEDIMENTOS.CD_PROCEDIMENTO_FINAL
        LEFT JOIN DBAMV.TIP_RES TR ON A.CD_TIP_RES = TR.CD_TIP_RES
    WHERE A.TP_ATENDIMENTO = 'I' AND A.CD_MULTI_EMPRESA = 40 AND A.HR_ATENDIMENTO <= p.DH_FIM AND NVL(A.HR_ALTA, SYSDATE) >= p.DH_INICIO

    UNION ALL

    -- Segunda Consulta: Apenas Urgências
    SELECT
        A.CD_ATENDIMENTO, A.TP_ATENDIMENTO, P.CD_PACIENTE, P.NM_PACIENTE, A.HR_ATENDIMENTO, A.HR_ALTA, E.DS_ESPECIALID, UI.DS_UNID_INT,
        (NVL(A.HR_ALTA, p.DH_FIM) - A.HR_ATENDIMENTO) AS PERMANENCIA_DIAS_CALC,
        A.CD_TIPO_INTERNACAO, SC.DS_TIPO_RISCO, chamada_classif.dh_processo AS DH_CHAMADA_CLASSIF,
        classif_inicio.dh_processo  AS DH_INICIO_CLASSIF, classif_fim.dh_processo AS DH_FIM_CLASSIF,
        CID_ADM.DS_CID, PROCEDIMENTOS.CD_PROCEDIMENTO_FINAL, SUS.DS_PROCEDIMENTO, MA.DS_MOT_ALT,
        TR.SN_OBITO, P.DT_NASCIMENTO, P.TP_SEXO, SUS.CD_GRUPO_PROCEDIMENTO, A.CD_ESPECIALID,
        p.DH_FIM AS DH_FIM_PERIODO
    FROM
        DBAMV.ATENDIME A
        CROSS JOIN params p
        LEFT JOIN DBAMV.PACIENTE P ON A.CD_PACIENTE = P.CD_PACIENTE
        LEFT JOIN DBAMV.MOT_ALT MA ON A.CD_MOT_ALT = MA.CD_MOT_ALT
        LEFT JOIN DBAMV.ESPECIALID E ON A.CD_ESPECIALID = E.CD_ESPECIALID
        LEFT JOIN DBAMV.TIPO_INTERNACAO TI ON A.CD_TIPO_INTERNACAO = TI.CD_TIPO_INTERNACAO
        LEFT JOIN DBAMV.LEITO L ON A.CD_LEITO = L.CD_LEITO
        LEFT JOIN DBAMV.UNID_INT UI ON UI.CD_UNID_INT = L.CD_UNID_INT
        LEFT JOIN DBAMV.TRIAGEM_ATENDIMENTO STA ON A.CD_ATENDIMENTO = STA.CD_ATENDIMENTO
        LEFT JOIN DBAMV.SACR_CLASSIFICACAO SC ON STA.CD_CLASSIFICACAO = SC.CD_CLASSIFICACAO
        LEFT JOIN DBAMV.CID CID_ADM ON A.CD_CID = CID_ADM.CD_CID
        LEFT JOIN (SELECT cd_triagem_atendimento, MIN(dh_processo) AS dh_processo FROM SACR_TEMPO_PROCESSO WHERE cd_tipo_tempo_processo = 10 GROUP BY cd_triagem_atendimento) chamada_classif ON chamada_classif.cd_triagem_atendimento = STA.cd_triagem_atendimento
        LEFT JOIN (SELECT cd_triagem_atendimento, MIN(dh_processo) AS dh_processo FROM SACR_TEMPO_PROCESSO WHERE cd_tipo_tempo_processo = 11 GROUP BY cd_triagem_atendimento) classif_inicio  ON classif_inicio.cd_triagem_atendimento = STA.cd_triagem_atendimento
        LEFT JOIN (SELECT cd_triagem_atendimento, MAX(dh_processo) AS dh_processo FROM SACR_TEMPO_PROCESSO WHERE cd_tipo_tempo_processo = 12 GROUP BY cd_triagem_atendimento) classif_fim        ON classif_fim.cd_triagem_atendimento = STA.cd_triagem_atendimento
        LEFT JOIN (
            SELECT A.CD_ATENDIMENTO, CASE WHEN AIHE.CD_PROCEDIMENTO_MUDANCA IS NOT NULL THEN AIHE.CD_PROCEDIMENTO_MUDANCA WHEN AIHE.CD_PROCEDIMENTO_MUDANCA IS NULL AND AIH.CD_PROCEDIMENTO IS NOT NULL THEN AIH.CD_PROCEDIMENTO WHEN AIH.CD_PROCEDIMENTO IS NULL AND AIHE.CD_PROCEDIMENTO_MUDANCA IS NULL AND A.CD_PROCEDIMENTO IS NOT NULL THEN A.CD_PROCEDIMENTO END AS CD_PROCEDIMENTO_FINAL
            FROM DBAMV.ATENDIME A
            LEFT JOIN DBAMV.LAUDO_AIH AIH ON AIH.CD_ATENDIMENTO = A.CD_ATENDIMENTO
            LEFT JOIN DBAMV.LAUDO_AIH_ESPECIAL AIHE ON AIHE.CD_LAUDO = AIH.CD_LAUDO
            WHERE (AIH.CD_LAUDO IN (SELECT MAX(AIH2.CD_LAUDO) FROM DBAMV.LAUDO_AIH AIH2 WHERE AIH2.CD_ATENDIMENTO = A.CD_ATENDIMENTO) OR AIH.CD_LAUDO IS NULL)
        ) PROCEDIMENTOS ON PROCEDIMENTOS.CD_ATENDIMENTO = A.CD_ATENDIMENTO
        LEFT JOIN DBAMV.PROCEDIMENTO_SUS SUS ON SUS.CD_PROCEDIMENTO = PROCEDIMENTOS.CD_PROCEDIMENTO_FINAL
        LEFT JOIN DBAMV.TIP_RES TR ON A.CD_TIP_RES = TR.CD_TIP_RES
    WHERE A.TP_ATENDIMENTO = 'U' AND A.CD_MULTI_EMPRESA = 40 AND A.HR_ATENDIMENTO BETWEEN p.DH_INICIO AND p.DH_FIM
),
dados_unicos AS (
    SELECT
        d.*,
        ROW_NUMBER() OVER (PARTITION BY d.CD_ATENDIMENTO ORDER BY d.HR_ATENDIMENTO DESC) as rn
    FROM dados_com_duplicatas d
)
SELECT
    TO_CHAR(CD_PACIENTE) AS CD_PACIENTE,
    TO_CHAR(CD_ATENDIMENTO) AS CD_ATENDIMENTO,
    TP_ATENDIMENTO,
    NM_PACIENTE,
    HR_ATENDIMENTO,
    CASE WHEN HR_ALTA > DH_FIM_PERIODO THEN NULL ELSE HR_ALTA END AS HR_ALTA,
    DS_ESPECIALID AS ESPECIALIDADE_ENTRADA,
    DS_UNID_INT AS UNIDADE_INTERNACAO,
    TO_CHAR(PERMANENCIA_DIAS_CALC, '999990.99') AS PERMANENCIA_DIAS,
    CASE WHEN CD_TIPO_INTERNACAO IN (43, 58, 60, 66, 67, 68, 69, 71) THEN 'Não Regulado (Espontâneo)' ELSE 'Regulado' END AS TIPO_DEMANDA,
    COALESCE(DS_TIPO_RISCO, 'Sem Classificação') AS CLASSIFICACAO_RISCO_PS,
    DH_CHAMADA_CLASSIF,
    DH_INICIO_CLASSIF,
    DH_FIM_CLASSIF,
    DS_CID AS CID_ADMISSAO_DESCRICAO,
    DS_PROCEDIMENTO AS PROCEDIMENTO_PRINCIPAL_DESC,
    (SELECT CASE WHEN EXISTS (SELECT 1 FROM DBAMV.AVISO_CIRURGIA ac_check WHERE ac_check.cd_atendimento = du.CD_ATENDIMENTO AND ac_check.tp_situacao = 'R' AND ac_check.tp_cirurgias IN ('U', 'M')) THEN 'Cirurgia de Urgência' WHEN EXISTS (SELECT 1 FROM DBAMV.AVISO_CIRURGIA ac_check WHERE ac_check.cd_atendimento = du.CD_ATENDIMENTO AND ac_check.tp_situacao = 'R' AND ac_check.tp_cirurgias IN ('E', 'X')) THEN 'Cirurgia Eletiva' ELSE 'Sem Cirurgia' END FROM DUAL) AS STATUS_CIRURGICO,
    (SELECT COUNT(*) FROM DBAMV.AVISO_CIRURGIA ac_count WHERE ac_count.cd_atendimento = du.CD_ATENDIMENTO AND ac_count.tp_situacao = 'R') AS QTD_CIRURGIAS_REALIZADAS,
    CASE WHEN CD_PROCEDIMENTO_FINAL IS NOT NULL THEN (CASE WHEN CD_PROCEDIMENTO_FINAL IN ('0201010038', '0201010127', '0101010135', '0201010143', '0201010160', '0201010208', '0201010240', '0201010259', '0201010267', '0201010305', '0201010313', '0201010321', '0201010330', '0201010402', '0201010534', '0201010550', '0209040033', '0209040050', '0211050091', '0211050148') OR CD_GRUPO_PROCEDIMENTO = 4 AND CD_PROCEDIMENTO_FINAL NOT LIKE '0417%' THEN 'Saída Cirúrgica' WHEN CD_ESPECIALID = 28 AND (CD_PROCEDIMENTO_FINAL IN ('0201010275', '0211050105', '0304100013', '0304100021','0305020005', '0305020013', '0305020021', '0305020030', '0305020048', '0305020056') OR CD_PROCEDIMENTO_FINAL LIKE '0303%' OR CD_PROCEDIMENTO_FINAL LIKE '0308%') THEN 'Saída Neurológica' WHEN CD_PROCEDIMENTO_FINAL IN ('0201010275', '0211050105', '0304100013', '0304100021','0305020005', '0305020013', '0305020021', '0305020030', '0305020048', '0305020056') OR CD_PROCEDIMENTO_FINAL LIKE '0303%' OR CD_PROCEDIMENTO_FINAL LIKE '0308%' THEN 'Saída Clínica' ELSE 'Saída Clínica' END) ELSE NULL END AS CLASSIFICACAO_CLINICA_ALTA,
    DS_MOT_ALT AS MOTIVO_ALTA,
    CASE
        WHEN TP_ATENDIMENTO = 'I' AND (UPPER(DS_MOT_ALT) LIKE '%OBITO%' OR SN_OBITO = 'S') THEN 'Sim'
        WHEN TP_ATENDIMENTO = 'U' AND SN_OBITO = 'S' THEN 'Sim'
        ELSE 'Não'
    END AS ALTA_POR_OBITO,
    TRUNC(MONTHS_BETWEEN(HR_ATENDIMENTO, DT_NASCIMENTO) / 12) AS IDADE_NA_ADMISSAO,
    TP_SEXO
FROM dados_unicos du
WHERE rn = 1
ORDER BY
    HR_ATENDIMENTO DESC