-- SALDO DIARIO + CONSUMO - Estoque universal HUGO
-- EST_PRO = saldo atual de HOJE | MVTO_ESTOQUE + ITMVTO_ESTOQUE = movimentos diarios
-- SALDO_ESTIMADO: reconstroi saldo passado = saldo_hoje + soma(consumos futuros ao dia)
-- Transferencias internas (T) excluidas do calculo (net zero no consolidado)
-- Periodo: mes atual | Somente medicamentos
WITH saldo AS (
    SELECT
        ep.CD_PRODUTO,
        ROUND(SUM(ep.QT_ESTOQUE_ATUAL / NVL(NULLIF(Dbamv.verif_vl_fator_prod(ep.CD_PRODUTO), 0), 1)), 2) AS QT_ESTOQUE_ATUAL
    FROM DBAMV.EST_PRO ep
        INNER JOIN DBAMV.ESTOQUE estq ON estq.CD_ESTOQUE = ep.CD_ESTOQUE
    WHERE estq.CD_MULTI_EMPRESA = 40
    GROUP BY ep.CD_PRODUTO
),
consumo AS (
    SELECT
        itmv.CD_PRODUTO,
        TRUNC(mv.HR_MVTO_ESTOQUE) AS DIA,
        SUM(CASE WHEN mv.TP_MVTO_ESTOQUE = 'P' THEN itmv.QT_MOVIMENTACAO ELSE 0 END) AS SAIDA_PACIENTE,
        SUM(CASE WHEN mv.TP_MVTO_ESTOQUE = 'S' THEN itmv.QT_MOVIMENTACAO ELSE 0 END) AS SAIDA_SETOR,
        SUM(CASE WHEN mv.TP_MVTO_ESTOQUE = 'D' THEN itmv.QT_MOVIMENTACAO ELSE 0 END) AS DEV_SETOR,
        SUM(CASE WHEN mv.TP_MVTO_ESTOQUE = 'C' THEN itmv.QT_MOVIMENTACAO ELSE 0 END) AS DEV_PACIENTE,
        SUM(CASE WHEN mv.TP_MVTO_ESTOQUE IN ('P','S','V','X','E','O','M','B')
                 THEN itmv.QT_MOVIMENTACAO ELSE 0 END) AS TOTAL_SAIDAS,
        SUM(CASE WHEN mv.TP_MVTO_ESTOQUE IN ('D','C','N')
                 THEN itmv.QT_MOVIMENTACAO ELSE 0 END) AS TOTAL_ENTRADAS
    FROM DBAMV.MVTO_ESTOQUE mv
        INNER JOIN DBAMV.ITMVTO_ESTOQUE itmv ON itmv.CD_MVTO_ESTOQUE = mv.CD_MVTO_ESTOQUE
        INNER JOIN DBAMV.ESTOQUE estq ON estq.CD_ESTOQUE = mv.CD_ESTOQUE
    WHERE estq.CD_MULTI_EMPRESA = 40
      AND mv.HR_MVTO_ESTOQUE >= TRUNC(SYSDATE, 'MM')
    GROUP BY itmv.CD_PRODUTO, TRUNC(mv.HR_MVTO_ESTOQUE)
),
calc AS (
    SELECT
        c.CD_PRODUTO,
        prod.DS_PRODUTO,
        CAST(c.DIA AS DATE) AS DIA,
        CAST(c.SAIDA_PACIENTE AS NUMBER) AS SAIDA_PACIENTE,
        CAST(c.SAIDA_SETOR AS NUMBER) AS SAIDA_SETOR,
        CAST(c.DEV_SETOR AS NUMBER) AS DEV_SETOR,
        CAST(c.DEV_PACIENTE AS NUMBER) AS DEV_PACIENTE,
        CAST(c.TOTAL_SAIDAS AS NUMBER) AS TOTAL_SAIDAS,
        CAST(c.TOTAL_ENTRADAS AS NUMBER) AS TOTAL_ENTRADAS,
        CAST(c.TOTAL_SAIDAS - c.TOTAL_ENTRADAS AS NUMBER) AS CONSUMO_LIQUIDO,
        ROUND(NVL(s.QT_ESTOQUE_ATUAL, 0), 2) AS SALDO_ATUAL,
        ROUND(NVL(s.QT_ESTOQUE_ATUAL, 0)
            + NVL(SUM(c.TOTAL_SAIDAS - c.TOTAL_ENTRADAS) OVER (
                PARTITION BY c.CD_PRODUTO
                ORDER BY c.DIA
                ROWS BETWEEN 1 FOLLOWING AND UNBOUNDED FOLLOWING
              ), 0), 2) AS SALDO_ESTIMADO
    FROM consumo c
        INNER JOIN DBAMV.PRODUTO prod ON prod.CD_PRODUTO = c.CD_PRODUTO
        LEFT JOIN saldo s ON s.CD_PRODUTO = c.CD_PRODUTO
    WHERE prod.SN_MEDICAMENTO = 'S'
)
SELECT
    CD_PRODUTO,
    Initcap(DS_PRODUTO) AS PRODUTO,
    DIA,
    SAIDA_PACIENTE,
    SAIDA_SETOR,
    DEV_SETOR,
    DEV_PACIENTE,
    TOTAL_SAIDAS,
    TOTAL_ENTRADAS,
    CONSUMO_LIQUIDO,
    SALDO_ATUAL,
    SALDO_ESTIMADO
FROM calc
WHERE DIA <= TRUNC(SYSDATE)
ORDER BY DS_PRODUTO, DIA
