WITH
-- Mapeamento de setores
setores AS (
  SELECT 601 AS CD_UNID_INT, 'Emergência' AS DS_SETOR FROM dual UNION ALL
  SELECT 561 AS CD_UNID_INT, 'Emergência' AS DS_SETOR FROM dual UNION ALL
  SELECT 559 AS CD_UNID_INT, 'Emergência' AS DS_SETOR FROM dual UNION ALL
  SELECT 560 AS CD_UNID_INT, 'Emergência' AS DS_SETOR FROM dual UNION ALL
  SELECT 569 AS CD_UNID_INT, 'Emergência' AS DS_SETOR FROM dual UNION ALL
  SELECT 568 AS CD_UNID_INT, 'Centro Cirúrgico' AS DS_SETOR FROM dual UNION ALL
  SELECT 564 AS CD_UNID_INT, 'UTI' AS DS_SETOR FROM dual UNION ALL
  SELECT 565 AS CD_UNID_INT, 'UTI' AS DS_SETOR FROM dual UNION ALL
  SELECT 566 AS CD_UNID_INT, 'UTI' AS DS_SETOR FROM dual UNION ALL
  SELECT 567 AS CD_UNID_INT, 'UTI' AS DS_SETOR FROM dual UNION ALL
  SELECT 558 AS CD_UNID_INT, 'Enfermaria' AS DS_SETOR FROM dual UNION ALL
  SELECT 562 AS CD_UNID_INT, 'Enfermaria' AS DS_SETOR FROM dual UNION ALL
  SELECT 563 AS CD_UNID_INT, 'Enfermaria' AS DS_SETOR FROM dual UNION ALL
  SELECT 570 AS CD_UNID_INT, 'Enfermaria' AS DS_SETOR FROM dual
),
-- Parâmetros de data
params AS (
  SELECT ADD_MONTHS(TRUNC(TO_DATE('2025-10-12', 'YYYY-MM-DD')), -11) AS DH_INICIO,
         TO_DATE('2025-10-12 19:56:17', 'YYYY-MM-DD HH24:MI:SS') AS DH_FIM
  FROM dual
),
-- Etapa 1: Buscar as solicitações resolvidas
solicitacoes_base AS (
  SELECT
    stl.CD_ATENDIMENTO,
    stl.DH_SOLICITACAO,
    stl.CD_MOV_INT,
    stl.CD_TIP_ACOM,
    (SELECT l.CD_UNID_INT
     FROM DBAMV.MOV_INT m JOIN DBAMV.LEITO l ON m.CD_LEITO = l.CD_LEITO
     WHERE m.CD_ATENDIMENTO = stl.CD_ATENDIMENTO
       AND m.HR_MOV_INT <= stl.DH_SOLICITACAO
     ORDER BY m.HR_MOV_INT DESC FETCH FIRST 1 ROWS ONLY
    ) AS CD_UNID_INT_ORIGEM
  FROM
    DBAMV.SOLIC_TRANSFERENCIA_LEITO stl
    JOIN params ON stl.DH_SOLICITACAO BETWEEN params.DH_INICIO AND params.DH_FIM
  WHERE
    stl.TP_SITUACAO = 'R'
    AND stl.CD_MOV_INT IS NOT NULL
),
-- Etapa 2: Preparar MOV_INT com data/hora combinadas (CORRIGIDO)
mov_int_completo AS (
  SELECT
    mi.CD_MOV_INT,
    mi.CD_ATENDIMENTO,
    mi.CD_LEITO,
    mi.SN_RESERVA,
    mi.DT_MOV_INT,
    mi.HR_MOV_INT,
    mi.DT_LIB_MOV,
    mi.HR_LIB_MOV,
    -- CORRIGIDO: Usando o método seguro para evitar erros de cálculo
    TO_DATE(TO_CHAR(mi.DT_MOV_INT, 'DD/MM/YYYY') || ' ' || TO_CHAR(mi.HR_MOV_INT, 'HH24:MI:SS'), 'DD/MM/YYYY HH24:MI:SS') AS DH_MOVIMENTACAO,
    -- CORRIGIDO: Usando o método seguro também para a data de liberação
    TO_DATE(TO_CHAR(mi.DT_LIB_MOV, 'DD/MM/YYYY') || ' ' || TO_CHAR(mi.HR_LIB_MOV, 'HH24:MI:SS'), 'DD/MM/YYYY HH24:MI:SS') AS DH_LIBERACAO
  FROM DBAMV.MOV_INT mi
),
-- Etapa 3: Vincular cada solicitação à sua reserva anterior específica
reservas_vinculadas AS (
  SELECT
    s.CD_ATENDIMENTO,
    s.DH_SOLICITACAO,
    s.CD_MOV_INT AS CD_MOV_INT_FINAL,
    (
      SELECT MAX(mi_res.CD_MOV_INT)
      FROM DBAMV.MOV_INT mi_res
      WHERE mi_res.CD_ATENDIMENTO = s.CD_ATENDIMENTO
        AND mi_res.CD_MOV_INT < s.CD_MOV_INT
        AND mi_res.SN_RESERVA = 'S'
    ) AS CD_MOV_INT_RESERVA
  FROM solicitacoes_base s
)
-- Etapa 4: Juntar tudo para montar o relatório final
SELECT
  pac.NM_PACIENTE,
  rv.CD_ATENDIMENTO,
  origem.DS_SETOR AS GRUPO_SETOR_ORIGEM,
  unid_origem.DS_UNID_INT AS SETOR_ORIGEM_ESPECIFICO,
  ta.DS_TIP_ACOM AS ACOMODACAO_SOLICITADA,
  destino.DS_SETOR AS GRUPO_SETOR_DESTINO_FINAL,
  unid_destino.DS_UNID_INT AS SETOR_DESTINO_ESPECIFICO,
  TO_CHAR(rv.DH_SOLICITACAO, 'DD/MM/YY HH24:MI') AS HR_SOLICITACAO,
  CASE WHEN rv.CD_MOV_INT_RESERVA IS NOT NULL THEN 'SIM' ELSE 'NAO' END AS HOUVE_RESERVA,
  TO_CHAR(mi_reserva.DH_MOVIMENTACAO, 'DD/MM/YY HH24:MI') AS HR_RESERVA_LEITO,
  TO_CHAR(mi_reserva.DH_LIBERACAO, 'DD/MM/YY HH24:MI') AS HR_ACOMODACAO_EFETIVA,
  ROUND((mi_reserva.DH_LIBERACAO - rv.DH_SOLICITACAO) * 24, 1) AS TEMPO_TOTAL_SOLICITACAO_ACOMODACAO_HORAS,
  ROUND((mi_reserva.DH_MOVIMENTACAO - rv.DH_SOLICITACAO) * 24, 1) AS TEMPO_SOLICITACAO_RESERVA_HORAS,
  ROUND((mi_reserva.DH_LIBERACAO - mi_reserva.DH_MOVIMENTACAO) * 24, 1) AS TEMPO_RESERVA_ACOMODACAO_HORAS
FROM
  reservas_vinculadas rv
  JOIN solicitacoes_base s ON rv.CD_ATENDIMENTO = s.CD_ATENDIMENTO AND rv.DH_SOLICITACAO = s.DH_SOLICITACAO
  LEFT JOIN mov_int_completo mi_reserva ON rv.CD_MOV_INT_RESERVA = mi_reserva.CD_MOV_INT
  JOIN DBAMV.ATENDIME atd ON rv.CD_ATENDIMENTO = atd.CD_ATENDIMENTO
  JOIN DBAMV.PACIENTE pac ON atd.CD_PACIENTE = pac.CD_PACIENTE
  LEFT JOIN setores origem ON s.CD_UNID_INT_ORIGEM = origem.CD_UNID_INT
  LEFT JOIN DBAMV.UNID_INT unid_origem ON s.CD_UNID_INT_ORIGEM = unid_origem.CD_UNID_INT
  JOIN mov_int_completo mi_dest ON rv.CD_MOV_INT_FINAL = mi_dest.CD_MOV_INT
  LEFT JOIN DBAMV.LEITO leito_destino ON COALESCE(mi_reserva.CD_LEITO, mi_dest.CD_LEITO) = leito_destino.CD_LEITO
  LEFT JOIN setores destino ON leito_destino.CD_UNID_INT = destino.CD_UNID_INT
  LEFT JOIN DBAMV.UNID_INT unid_destino ON leito_destino.CD_UNID_INT = unid_destino.CD_UNID_INT
  LEFT JOIN DBAMV.TIP_ACOM ta ON s.CD_TIP_ACOM = ta.CD_TIP_ACOM
WHERE
  atd.CD_MULTI_EMPRESA = 40
ORDER BY
  rv.CD_ATENDIMENTO ASC,
  rv.DH_SOLICITACAO ASC