-- =============================================
-- MAPA CIRURGICO - Visao da Agenda por Sala/Horario
-- Fonte: AGE_CIR (agendamento real)
-- Parametros Portlet: $pgmvDataIni$ / $pgmvDataFim$
-- Unidade: CD_MULTI_EMPRESA = 40 (HUGO)
-- =============================================
WITH BASE AS (
    SELECT
        ag.CD_AGE_CIR,
        ag.DT_INICIO_AGE_CIR,
        ag.DT_FINAL_AGE_CIR,
        ag.TP_AGENDAMENTO,
        ROUND((ag.DT_FINAL_AGE_CIR - ag.DT_INICIO_AGE_CIR) * 24 * 60) AS DURACAO_AGENDADA_MIN,
        sc.DS_SAL_CIR,
        em.DS_EQUIPE_MEDICA,
        ac.CD_AVISO_CIRURGIA,
        pac.NM_PACIENTE,
        ac.TP_SITUACAO,
        ac.TP_CIRURGIAS,
        ac.DT_REALIZACAO,
        ac.DT_INICIO_CIRURGIA,
        ac.DT_FIM_CIRURGIA,
        COALESCE(cir.DS_CIRURGIA, 'N/I') AS DS_CIRURGIA,
        esp.DS_ESPECIALID,
        pa.NM_PRESTADOR AS CIRURGIAO_PRINCIPAL
    FROM DBAMV.AGE_CIR ag
    INNER JOIN DBAMV.AVISO_CIRURGIA ac ON ac.CD_AVISO_CIRURGIA = ag.CD_AVISO_CIRURGIA
    INNER JOIN DBAMV.ATENDIME atd ON atd.CD_ATENDIMENTO = ac.CD_ATENDIMENTO
    INNER JOIN DBAMV.PACIENTE pac ON pac.CD_PACIENTE = ac.CD_PACIENTE
    LEFT JOIN DBAMV.SAL_CIR sc ON sc.CD_SAL_CIR = ag.CD_SAL_CIR
    LEFT JOIN DBAMV.EQUIPE_MEDICA em ON em.CD_EQUIPE_MEDICA = ag.CD_EQUIPE_MEDICA
    LEFT JOIN DBAMV.CIRURGIA_AVISO ca ON ca.CD_AVISO_CIRURGIA = ac.CD_AVISO_CIRURGIA
    LEFT JOIN DBAMV.CIRURGIA cir ON cir.CD_CIRURGIA = ca.CD_CIRURGIA
    LEFT JOIN DBAMV.ESPECIALID esp ON esp.CD_ESPECIALID = ca.CD_ESPECIALID
    LEFT JOIN DBAMV.PRESTADOR_AVISO pa ON pa.CD_AVISO_CIRURGIA = ac.CD_AVISO_CIRURGIA
                                       AND pa.SN_PRINCIPAL = 'S'
                                       AND pa.CD_CIRURGIA_AVISO = ca.CD_CIRURGIA_AVISO
    WHERE atd.CD_MULTI_EMPRESA = 40
      AND ag.DT_INICIO_AGE_CIR BETWEEN $pgmvDataIni$ AND $pgmvDataFim$
)
SELECT
    b.CD_AGE_CIR,
    b.DT_INICIO_AGE_CIR AS INICIO_AGENDADO,
    b.DT_FINAL_AGE_CIR AS FIM_AGENDADO,
    b.DURACAO_AGENDADA_MIN,
    b.DS_SAL_CIR,
    b.DS_EQUIPE_MEDICA,
    b.CD_AVISO_CIRURGIA,
    b.NM_PACIENTE,
    CASE b.TP_SITUACAO
        WHEN 'A' THEN 'Em Aviso'
        WHEN 'R' THEN 'Realizada'
        WHEN 'C' THEN 'Cancelada'
        WHEN 'G' THEN 'Agendada'
        WHEN 'T' THEN 'Checagem'
        WHEN 'P' THEN 'Pre-Agendamento'
        ELSE b.TP_SITUACAO
    END AS SITUACAO,
    CASE
        WHEN b.TP_CIRURGIAS = 'E' THEN 'Eletiva'
        WHEN b.TP_CIRURGIAS IN ('U','M') THEN 'Urgencia/Emergencia'
        ELSE 'Nao Classificada'
    END AS TIPO_CIRURGIA,
    LISTAGG(DISTINCT b.DS_CIRURGIA, '; ') WITHIN GROUP (ORDER BY b.DS_CIRURGIA) AS PROCEDIMENTOS,
    LISTAGG(DISTINCT b.DS_ESPECIALID, '; ') WITHIN GROUP (ORDER BY b.DS_ESPECIALID) AS ESPECIALIDADES,
    MAX(b.CIRURGIAO_PRINCIPAL) AS CIRURGIAO_PRINCIPAL,
    b.DT_REALIZACAO,
    b.DT_INICIO_CIRURGIA,
    b.DT_FIM_CIRURGIA,
    b.TP_AGENDAMENTO
FROM BASE b
GROUP BY
    b.CD_AGE_CIR, b.DT_INICIO_AGE_CIR, b.DT_FINAL_AGE_CIR,
    b.DURACAO_AGENDADA_MIN, b.DS_SAL_CIR, b.DS_EQUIPE_MEDICA,
    b.CD_AVISO_CIRURGIA, b.NM_PACIENTE, b.TP_SITUACAO, b.TP_CIRURGIAS,
    b.DT_REALIZACAO, b.DT_INICIO_CIRURGIA, b.DT_FIM_CIRURGIA, b.TP_AGENDAMENTO
ORDER BY
    b.DT_INICIO_AGE_CIR,
    b.DS_SAL_CIR
