-- =============================================
-- OCUPACAO DE SALAS - Baseado na Agenda (AGE_CIR)
-- Parametros Portlet: $pgmvDataIni$ / $pgmvDataFim$
-- Unidade: CD_MULTI_EMPRESA = 40 (HUGO)
-- =============================================
SELECT
    sc.DS_SAL_CIR,
    COUNT(*) AS QTD_AGENDAMENTOS,
    SUM(CASE WHEN ac.TP_SITUACAO = 'R' THEN 1 ELSE 0 END) AS QTD_REALIZADAS,
    SUM(CASE WHEN ac.TP_SITUACAO = 'C' THEN 1 ELSE 0 END) AS QTD_CANCELADAS,
    SUM(CASE WHEN ac.TP_SITUACAO = 'G' THEN 1 ELSE 0 END) AS QTD_AGENDADAS_PENDENTES,
    COUNT(DISTINCT TRUNC(ag.DT_INICIO_AGE_CIR)) AS QTD_DIAS_COM_AGENDA,

    -- Tempo total agendado
    CAST(ROUND(SUM((ag.DT_FINAL_AGE_CIR - ag.DT_INICIO_AGE_CIR) * 24), 1) AS NUMBER(10,1)) AS TOTAL_HORAS_AGENDADAS,

    -- Tempo real ocupado (so realizadas)
    CAST(ROUND(SUM(
        CASE WHEN ac.TP_SITUACAO = 'R' AND ac.DT_SAIDA_SAL_CIR IS NOT NULL AND ac.DT_INICIO_ANESTESIA IS NOT NULL
             THEN (ac.DT_SAIDA_SAL_CIR - ac.DT_INICIO_ANESTESIA) * 24
             ELSE 0
        END
    ), 1) AS NUMBER(10,1)) AS TOTAL_HORAS_REAIS,

    -- Medias (so realizadas)
    CAST(ROUND(AVG(
        CASE WHEN ac.TP_SITUACAO = 'R' AND ac.DT_SAIDA_SAL_CIR IS NOT NULL AND ac.DT_INICIO_ANESTESIA IS NOT NULL
             THEN (ac.DT_SAIDA_SAL_CIR - ac.DT_INICIO_ANESTESIA) * 24 * 60
        END
    )) AS NUMBER(10,0)) AS MEDIA_PERMANENCIA_MIN,

    CAST(ROUND(AVG(
        CASE WHEN ac.TP_SITUACAO = 'R' AND ac.DT_FIM_LIMPEZA IS NOT NULL AND ac.DT_INICIO_LIMPEZA IS NOT NULL
             THEN (ac.DT_FIM_LIMPEZA - ac.DT_INICIO_LIMPEZA) * 24 * 60
        END
    )) AS NUMBER(10,0)) AS MEDIA_LIMPEZA_MIN,

    -- Media cirurgias por dia
    CAST(ROUND(COUNT(*) / NULLIF(COUNT(DISTINCT TRUNC(ag.DT_INICIO_AGE_CIR)), 0), 1) AS NUMBER(10,1)) AS MEDIA_AGENDAMENTOS_DIA,

    -- Taxa cancelamento
    CAST(ROUND(SUM(CASE WHEN ac.TP_SITUACAO = 'C' THEN 1 ELSE 0 END) * 100.0
        / NULLIF(COUNT(*), 0), 1) AS NUMBER(10,1)) AS PCT_CANCELAMENTO

FROM DBAMV.AGE_CIR ag
INNER JOIN DBAMV.AVISO_CIRURGIA ac ON ac.CD_AVISO_CIRURGIA = ag.CD_AVISO_CIRURGIA
INNER JOIN DBAMV.ATENDIME atd ON atd.CD_ATENDIMENTO = ac.CD_ATENDIMENTO
INNER JOIN DBAMV.SAL_CIR sc ON sc.CD_SAL_CIR = ag.CD_SAL_CIR
WHERE atd.CD_MULTI_EMPRESA = 40
  AND ag.DT_INICIO_AGE_CIR BETWEEN $pgmvDataIni$ AND $pgmvDataFim$
GROUP BY sc.DS_SAL_CIR
ORDER BY QTD_AGENDAMENTOS DESC
