-- =============================================
-- CANCELAMENTOS E SUSPENSOES - Baseado na Agenda (AGE_CIR)
-- Parametros Portlet: $pgmvDataIni$ / $pgmvDataFim$
-- Unidade: CD_MULTI_EMPRESA = 40 (HUGO)
-- =============================================
WITH BASE AS (
    SELECT
        ag.CD_AGE_CIR,
        ag.DT_INICIO_AGE_CIR,
        ag.DT_FINAL_AGE_CIR,
        sc.DS_SAL_CIR,
        ac.CD_AVISO_CIRURGIA,
        pac.NM_PACIENTE,
        ac.TP_SITUACAO,
        ac.TP_CIRURGIAS,
        ac.SN_SUSPENSAO,
        ac.DT_CANCELAMENTO,
        mc_canc.DS_MOT_CANC AS MOTIVO_CANCELAMENTO,
        mc_canc.TP_MOT_CANC,
        mc_atr.DS_MOT_CANC AS MOTIVO_ATRASO,
        COALESCE(cir.DS_CIRURGIA, 'N/I') AS DS_CIRURGIA,
        esp.DS_ESPECIALID
    FROM DBAMV.AGE_CIR ag
    INNER JOIN DBAMV.AVISO_CIRURGIA ac ON ac.CD_AVISO_CIRURGIA = ag.CD_AVISO_CIRURGIA
    INNER JOIN DBAMV.ATENDIME atd ON atd.CD_ATENDIMENTO = ac.CD_ATENDIMENTO
    INNER JOIN DBAMV.PACIENTE pac ON pac.CD_PACIENTE = ac.CD_PACIENTE
    LEFT JOIN DBAMV.SAL_CIR sc ON sc.CD_SAL_CIR = ag.CD_SAL_CIR
    LEFT JOIN DBAMV.MOT_CANC mc_canc ON mc_canc.CD_MOT_CANC = ac.CD_MOT_CANC
    LEFT JOIN DBAMV.MOT_CANC mc_atr ON mc_atr.CD_MOT_CANC = ac.CD_MOT_CANC_ATRASO
    LEFT JOIN DBAMV.CIRURGIA_AVISO ca ON ca.CD_AVISO_CIRURGIA = ac.CD_AVISO_CIRURGIA
    LEFT JOIN DBAMV.CIRURGIA cir ON cir.CD_CIRURGIA = ca.CD_CIRURGIA
    LEFT JOIN DBAMV.ESPECIALID esp ON esp.CD_ESPECIALID = ca.CD_ESPECIALID
    WHERE atd.CD_MULTI_EMPRESA = 40
      AND ag.DT_INICIO_AGE_CIR BETWEEN $pgmvDataIni$ AND $pgmvDataFim$
      AND (ac.TP_SITUACAO = 'C' OR ac.SN_SUSPENSAO = 'S')
)
SELECT
    b.CD_AGE_CIR,
    b.DT_INICIO_AGE_CIR AS INICIO_AGENDADO,
    b.DS_SAL_CIR,
    b.CD_AVISO_CIRURGIA,
    b.NM_PACIENTE,
    CASE b.TP_SITUACAO
        WHEN 'C' THEN 'Cancelada'
        ELSE 'Suspensa'
    END AS SITUACAO,
    CASE
        WHEN b.TP_CIRURGIAS = 'E' THEN 'Eletiva'
        WHEN b.TP_CIRURGIAS IN ('U','M') THEN 'Urgencia/Emergencia'
        ELSE 'Nao Classificada'
    END AS TIPO_CIRURGIA,
    b.MOTIVO_CANCELAMENTO,
    CASE b.TP_MOT_CANC
        WHEN 'A' THEN 'Administrativo'
        WHEN 'M' THEN 'Medico'
        WHEN 'P' THEN 'Paciente'
        WHEN 'T' THEN 'Transferencia'
        WHEN 'C' THEN 'Cancelamento'
        ELSE b.TP_MOT_CANC
    END AS TIPO_MOTIVO,
    b.MOTIVO_ATRASO,
    LISTAGG(DISTINCT b.DS_CIRURGIA, '; ') WITHIN GROUP (ORDER BY b.DS_CIRURGIA) AS PROCEDIMENTOS,
    LISTAGG(DISTINCT b.DS_ESPECIALID, '; ') WITHIN GROUP (ORDER BY b.DS_ESPECIALID) AS ESPECIALIDADES,
    b.DT_CANCELAMENTO,
    b.SN_SUSPENSAO
FROM BASE b
GROUP BY
    b.CD_AGE_CIR, b.DT_INICIO_AGE_CIR, b.DT_FINAL_AGE_CIR, b.DS_SAL_CIR,
    b.CD_AVISO_CIRURGIA, b.NM_PACIENTE, b.TP_SITUACAO, b.TP_CIRURGIAS,
    b.SN_SUSPENSAO, b.MOTIVO_CANCELAMENTO, b.TP_MOT_CANC, b.MOTIVO_ATRASO,
    b.DT_CANCELAMENTO
ORDER BY
    b.DT_CANCELAMENTO DESC NULLS LAST,
    b.DT_INICIO_AGE_CIR DESC
