-- =============================================
-- PERFORMANCE CIRURGICA POR SALA - Agendado vs Real
-- Fonte: AGE_CIR (agendamento) + AVISO_CIRURGIA (execucao)
-- Parametros Portlet: $pgmvDataIni$ / $pgmvDataFim$
-- Unidade: CD_MULTI_EMPRESA = 40 (HUGO)
-- Somente cirurgias REALIZADAS
-- =============================================
WITH DADOS AS (
    SELECT
        sc.DS_SAL_CIR,
        ag.CD_AGE_CIR,
        -- Tempo agendado
        ROUND((ag.DT_FINAL_AGE_CIR - ag.DT_INICIO_AGE_CIR) * 24 * 60) AS AGENDADO_MIN,
        -- Tempo real de cirurgia
        CASE WHEN ac.DT_FIM_CIRURGIA IS NOT NULL AND ac.DT_INICIO_CIRURGIA IS NOT NULL
             THEN ROUND((ac.DT_FIM_CIRURGIA - ac.DT_INICIO_CIRURGIA) * 24 * 60)
        END AS CIRURGIA_REAL_MIN,
        -- Tempo real de anestesia
        CASE WHEN ac.DT_FIM_ANESTESIA IS NOT NULL AND ac.DT_INICIO_ANESTESIA IS NOT NULL
             THEN ROUND((ac.DT_FIM_ANESTESIA - ac.DT_INICIO_ANESTESIA) * 24 * 60)
        END AS ANESTESIA_MIN,
        -- Tempo de limpeza
        CASE WHEN ac.DT_FIM_LIMPEZA IS NOT NULL AND ac.DT_INICIO_LIMPEZA IS NOT NULL
             THEN ROUND((ac.DT_FIM_LIMPEZA - ac.DT_INICIO_LIMPEZA) * 24 * 60)
        END AS LIMPEZA_MIN,
        -- Permanencia total na sala
        CASE WHEN ac.DT_SAIDA_SAL_CIR IS NOT NULL AND ac.DT_INICIO_ANESTESIA IS NOT NULL
             THEN ROUND((ac.DT_SAIDA_SAL_CIR - ac.DT_INICIO_ANESTESIA) * 24 * 60)
        END AS PERMANENCIA_MIN,
        -- Atraso
        CASE WHEN ac.CD_MOT_CANC_ATRASO IS NOT NULL THEN 1 ELSE 0 END AS FL_ATRASO,
        mc_atr.DS_MOT_CANC AS MOTIVO_ATRASO
    FROM DBAMV.AGE_CIR ag
    INNER JOIN DBAMV.AVISO_CIRURGIA ac ON ac.CD_AVISO_CIRURGIA = ag.CD_AVISO_CIRURGIA
    INNER JOIN DBAMV.ATENDIME atd ON atd.CD_ATENDIMENTO = ac.CD_ATENDIMENTO
    LEFT JOIN DBAMV.SAL_CIR sc ON sc.CD_SAL_CIR = ag.CD_SAL_CIR
    LEFT JOIN DBAMV.MOT_CANC mc_atr ON mc_atr.CD_MOT_CANC = ac.CD_MOT_CANC_ATRASO
    WHERE atd.CD_MULTI_EMPRESA = 40
      AND ac.TP_SITUACAO = 'R'
      AND ag.DT_INICIO_AGE_CIR BETWEEN $pgmvDataIni$ AND $pgmvDataFim$
),
ATRASO_RANK AS (
    SELECT
        DS_SAL_CIR,
        MOTIVO_ATRASO,
        COUNT(*) AS QTD,
        ROW_NUMBER() OVER (PARTITION BY DS_SAL_CIR ORDER BY COUNT(*) DESC) AS RN
    FROM DADOS
    WHERE FL_ATRASO = 1 AND MOTIVO_ATRASO IS NOT NULL
    GROUP BY DS_SAL_CIR, MOTIVO_ATRASO
)
SELECT
    d.DS_SAL_CIR,
    COUNT(*) AS QTD_REALIZADAS,

    -- Agendado vs Real
    CAST(ROUND(AVG(d.AGENDADO_MIN)) AS NUMBER(10,0)) AS MEDIA_AGENDADO_MIN,
    CAST(ROUND(AVG(d.PERMANENCIA_MIN)) AS NUMBER(10,0)) AS MEDIA_PERMANENCIA_REAL_MIN,
    CAST(ROUND(AVG(d.PERMANENCIA_MIN) - AVG(d.AGENDADO_MIN)) AS NUMBER(10,0)) AS DESVIO_MEDIO_MIN,

    -- Tempos medios
    CAST(ROUND(AVG(d.CIRURGIA_REAL_MIN)) AS NUMBER(10,0)) AS MEDIA_CIRURGIA_MIN,
    CAST(ROUND(AVG(d.ANESTESIA_MIN)) AS NUMBER(10,0)) AS MEDIA_ANESTESIA_MIN,
    CAST(ROUND(AVG(d.LIMPEZA_MIN)) AS NUMBER(10,0)) AS MEDIA_LIMPEZA_MIN,

    -- Min/Max cirurgia
    CAST(ROUND(MIN(d.CIRURGIA_REAL_MIN)) AS NUMBER(10,0)) AS MIN_CIRURGIA_MIN,
    CAST(ROUND(MAX(d.CIRURGIA_REAL_MIN)) AS NUMBER(10,0)) AS MAX_CIRURGIA_MIN,

    -- Atrasos
    SUM(d.FL_ATRASO) AS QTD_COM_ATRASO,
    CAST(ROUND(SUM(d.FL_ATRASO) * 100.0 / NULLIF(COUNT(*), 0), 1) AS NUMBER(10,1)) AS PCT_COM_ATRASO,
    MAX(ar.MOTIVO_ATRASO) AS MOTIVO_ATRASO_MAIS_COMUM

FROM DADOS d
LEFT JOIN ATRASO_RANK ar ON ar.DS_SAL_CIR = d.DS_SAL_CIR AND ar.RN = 1
GROUP BY d.DS_SAL_CIR
ORDER BY QTD_REALIZADAS DESC
