-- =============================================
-- AGENDA CENTRO CIRURGICO - ANALITICO COMPLETO
-- Fonte: AGE_CIR (agendamento) + AVISO_CIRURGIA + LOGs
-- Parametros Portlet: $pgmvDataIni$ / $pgmvDataFim$
-- Unidade: CD_MULTI_EMPRESA = 40 (HUGO)
-- Cada linha = 1 agendamento na agenda cirurgica
-- =============================================
WITH BASE AS (
    SELECT
        -- Agenda
        ag.CD_AGE_CIR,
        ag.DT_INICIO_AGE_CIR,
        ag.DT_FINAL_AGE_CIR,
        ag.TP_AGENDAMENTO,
        ROUND((ag.DT_FINAL_AGE_CIR - ag.DT_INICIO_AGE_CIR) * 24 * 60) AS DURACAO_AGENDADA_MIN,
        -- Sala
        sc.DS_SAL_CIR,
        -- Equipe medica
        em.DS_EQUIPE_MEDICA,
        -- Aviso cirurgia
        ac.CD_AVISO_CIRURGIA,
        ac.TP_SITUACAO,
        ac.TP_CIRURGIAS,
        ac.SN_SUSPENSAO,
        ac.DT_AVISO_CIRURGIA,
        ac.DT_REALIZACAO,
        ac.DT_CANCELAMENTO,
        ac.VL_TEMPO_PREVISTO,
        ac.VL_TEMPO_DURACAO,
        -- Timestamps reais
        ac.DT_INICIO_ANESTESIA,
        ac.DT_FIM_ANESTESIA,
        ac.DT_INICIO_CIRURGIA,
        ac.DT_FIM_CIRURGIA,
        ac.DT_INICIO_LIMPEZA,
        ac.DT_FIM_LIMPEZA,
        ac.DT_SAIDA_SAL_CIR,
        -- Duracoes reais em minutos
        CASE WHEN ac.DT_FIM_CIRURGIA IS NOT NULL AND ac.DT_INICIO_CIRURGIA IS NOT NULL
             THEN ROUND((ac.DT_FIM_CIRURGIA - ac.DT_INICIO_CIRURGIA) * 24 * 60)
        END AS DURACAO_CIRURGIA_REAL_MIN,
        CASE WHEN ac.DT_FIM_ANESTESIA IS NOT NULL AND ac.DT_INICIO_ANESTESIA IS NOT NULL
             THEN ROUND((ac.DT_FIM_ANESTESIA - ac.DT_INICIO_ANESTESIA) * 24 * 60)
        END AS DURACAO_ANESTESIA_MIN,
        CASE WHEN ac.DT_FIM_LIMPEZA IS NOT NULL AND ac.DT_INICIO_LIMPEZA IS NOT NULL
             THEN ROUND((ac.DT_FIM_LIMPEZA - ac.DT_INICIO_LIMPEZA) * 24 * 60)
        END AS DURACAO_LIMPEZA_MIN,
        CASE WHEN ac.DT_SAIDA_SAL_CIR IS NOT NULL AND ac.DT_INICIO_ANESTESIA IS NOT NULL
             THEN ROUND((ac.DT_SAIDA_SAL_CIR - ac.DT_INICIO_ANESTESIA) * 24 * 60)
        END AS PERMANENCIA_SALA_MIN,
        -- Paciente
        COALESCE(pac.NM_PACIENTE, ac.NM_PACIENTE) AS NM_PACIENTE,
        atd.TP_ATENDIMENTO,
        -- Cancelamento/Atraso
        mc_canc.DS_MOT_CANC AS MOTIVO_CANCELAMENTO,
        mc_canc.TP_MOT_CANC,
        mc_atr.DS_MOT_CANC AS MOTIVO_ATRASO,
        -- Procedimentos (para LISTAGG)
        COALESCE(cir.DS_CIRURGIA, 'N/I') AS DS_CIRURGIA,
        esp.DS_ESPECIALID,
        pa.NM_PRESTADOR AS CIRURGIAO_PRINCIPAL
    FROM DBAMV.AGE_CIR ag
    INNER JOIN DBAMV.AVISO_CIRURGIA ac ON ac.CD_AVISO_CIRURGIA = ag.CD_AVISO_CIRURGIA
    INNER JOIN DBAMV.ATENDIME atd ON atd.CD_ATENDIMENTO = ac.CD_ATENDIMENTO
    LEFT JOIN DBAMV.PACIENTE pac ON pac.CD_PACIENTE = ac.CD_PACIENTE
    LEFT JOIN DBAMV.SAL_CIR sc ON sc.CD_SAL_CIR = ag.CD_SAL_CIR
    LEFT JOIN DBAMV.EQUIPE_MEDICA em ON em.CD_EQUIPE_MEDICA = ag.CD_EQUIPE_MEDICA
    LEFT JOIN DBAMV.MOT_CANC mc_canc ON mc_canc.CD_MOT_CANC = ac.CD_MOT_CANC
    LEFT JOIN DBAMV.MOT_CANC mc_atr ON mc_atr.CD_MOT_CANC = ac.CD_MOT_CANC_ATRASO
    LEFT JOIN DBAMV.CIRURGIA_AVISO ca ON ca.CD_AVISO_CIRURGIA = ac.CD_AVISO_CIRURGIA
    LEFT JOIN DBAMV.CIRURGIA cir ON cir.CD_CIRURGIA = ca.CD_CIRURGIA
    LEFT JOIN DBAMV.ESPECIALID esp ON esp.CD_ESPECIALID = ca.CD_ESPECIALID
    LEFT JOIN DBAMV.PRESTADOR_AVISO pa ON pa.CD_AVISO_CIRURGIA = ac.CD_AVISO_CIRURGIA
                                       AND pa.SN_PRINCIPAL = 'S'
                                       AND pa.CD_CIRURGIA_AVISO = ca.CD_CIRURGIA_AVISO
    WHERE atd.CD_MULTI_EMPRESA = 40
      AND ag.DT_INICIO_AGE_CIR BETWEEN $pgmvDataIni$ AND $pgmvDataFim$
),
-- Agrupa por agendamento (resolve multiplicacao de CIRURGIA_AVISO/PRESTADOR)
AGRUPADO AS (
    SELECT
        b.CD_AGE_CIR,
        b.CD_AVISO_CIRURGIA,
        b.NM_PACIENTE,
        b.TP_ATENDIMENTO,
        b.TP_SITUACAO,
        b.TP_CIRURGIAS,
        b.SN_SUSPENSAO,
        b.DS_SAL_CIR,
        b.DS_EQUIPE_MEDICA,
        b.TP_AGENDAMENTO,
        b.DT_INICIO_AGE_CIR,
        b.DT_FINAL_AGE_CIR,
        b.DURACAO_AGENDADA_MIN,
        b.DT_AVISO_CIRURGIA,
        b.DT_REALIZACAO,
        b.DT_CANCELAMENTO,
        b.DT_INICIO_ANESTESIA,
        b.DT_FIM_ANESTESIA,
        b.DT_INICIO_CIRURGIA,
        b.DT_FIM_CIRURGIA,
        b.DT_INICIO_LIMPEZA,
        b.DT_FIM_LIMPEZA,
        b.DT_SAIDA_SAL_CIR,
        b.DURACAO_CIRURGIA_REAL_MIN,
        b.DURACAO_ANESTESIA_MIN,
        b.DURACAO_LIMPEZA_MIN,
        b.PERMANENCIA_SALA_MIN,
        MAX(b.VL_TEMPO_PREVISTO) AS TEMPO_PREVISTO,
        MAX(b.VL_TEMPO_DURACAO) AS TEMPO_DURACAO,
        LISTAGG(DISTINCT b.DS_CIRURGIA, '; ') WITHIN GROUP (ORDER BY b.DS_CIRURGIA) AS PROCEDIMENTOS,
        LISTAGG(DISTINCT b.DS_ESPECIALID, '; ') WITHIN GROUP (ORDER BY b.DS_ESPECIALID) AS ESPECIALIDADES,
        MAX(b.CIRURGIAO_PRINCIPAL) AS CIRURGIAO_PRINCIPAL,
        MAX(b.MOTIVO_CANCELAMENTO) AS MOTIVO_CANCELAMENTO,
        MAX(CASE b.TP_MOT_CANC
            WHEN 'A' THEN 'Administrativo'
            WHEN 'M' THEN 'Medico'
            WHEN 'P' THEN 'Paciente'
            WHEN 'T' THEN 'Transferencia'
            WHEN 'C' THEN 'Cancelamento'
            ELSE b.TP_MOT_CANC
        END) AS TIPO_MOTIVO_CANCELAMENTO,
        MAX(b.MOTIVO_ATRASO) AS MOTIVO_ATRASO
    FROM BASE b
    GROUP BY
        b.CD_AGE_CIR, b.CD_AVISO_CIRURGIA, b.NM_PACIENTE, b.TP_ATENDIMENTO,
        b.TP_SITUACAO, b.TP_CIRURGIAS, b.SN_SUSPENSAO,
        b.DS_SAL_CIR, b.DS_EQUIPE_MEDICA, b.TP_AGENDAMENTO,
        b.DT_INICIO_AGE_CIR, b.DT_FINAL_AGE_CIR, b.DURACAO_AGENDADA_MIN,
        b.DT_AVISO_CIRURGIA, b.DT_REALIZACAO, b.DT_CANCELAMENTO,
        b.DT_INICIO_ANESTESIA, b.DT_FIM_ANESTESIA,
        b.DT_INICIO_CIRURGIA, b.DT_FIM_CIRURGIA,
        b.DT_INICIO_LIMPEZA, b.DT_FIM_LIMPEZA, b.DT_SAIDA_SAL_CIR,
        b.DURACAO_CIRURGIA_REAL_MIN, b.DURACAO_ANESTESIA_MIN,
        b.DURACAO_LIMPEZA_MIN, b.PERMANENCIA_SALA_MIN
),
-- Log de evolucao: transicoes de status por aviso
LOG_EVOLUCAO AS (
    SELECT
        ev.CD_AVISO_CIRURGIA,
        COUNT(*) AS QTD_MUDANCAS_STATUS,
        SUM(CASE WHEN ev.TP_SITUACAO_ANTERIOR_AVI_CIR = 'G'
                  AND ev.TP_SITUACAO_ATUAL_AVI_CIR = 'P' THEN 1 ELSE 0 END) AS QTD_REVERSOES_GP,
        SUM(CASE WHEN ev.TP_SITUACAO_ATUAL_AVI_CIR = 'C' THEN 1 ELSE 0 END) AS QTD_VEZES_CANCELADO,
        MAX(ev.DT_ALTERACAO) AS DT_ULTIMA_MUDANCA,
        MAX(ev.CD_USUARIO_ALTERACAO) KEEP (DENSE_RANK LAST ORDER BY ev.DT_ALTERACAO) AS USUARIO_ULTIMA_MUDANCA,
        LISTAGG(
            COALESCE(ev.TP_SITUACAO_ANTERIOR_AVI_CIR, '?') || '->' || ev.TP_SITUACAO_ATUAL_AVI_CIR,
            ', '
        ) WITHIN GROUP (ORDER BY ev.DT_ALTERACAO) AS HISTORICO_STATUS
    FROM DBAMV.LOG_AVISO_CIRURGIA_EVOLUCAO ev
    WHERE ev.CD_MULTI_EMPRESA = 40
    GROUP BY ev.CD_AVISO_CIRURGIA
),
-- Log de suspensao: historico de suspensoes por aviso
LOG_SUSPENSAO AS (
    SELECT
        lss.CD_AVISO_CIRURGIA,
        COUNT(*) AS QTD_SUSPENSOES,
        MAX(lss.DT_HR_SUSPENSAO) AS DT_ULTIMA_SUSPENSAO,
        MAX(ms.DS_MOTIVO_SUSPENSAO) KEEP (DENSE_RANK LAST ORDER BY lss.DT_HR_SUSPENSAO)
            AS MOTIVO_ULTIMA_SUSPENSAO,
        SUM(CASE WHEN lss.DT_HR_RET_SUSPENSAO IS NOT NULL THEN 1 ELSE 0 END)
            AS QTD_SUSPENSOES_RETIRADAS
    FROM DBAMV.LOG_AVISO_CIRURGIA_SUSPENSAO lss
    LEFT JOIN DBAMV.MOTIVO_SUSPENSAO ms ON ms.CD_MOTIVO_SUSPENSAO = lss.CD_MOTIVO_SUSPENSAO
    GROUP BY lss.CD_AVISO_CIRURGIA
),
-- Log de aprovacao: status de aprovacao por aviso
LOG_APROVACAO AS (
    SELECT
        ap.CD_AVISO_CIRURGIA,
        COUNT(*) AS QTD_APROVACOES,
        SUM(CASE WHEN ap.STATUS = 'R' THEN 1 ELSE 0 END) AS QTD_REPROVACOES,
        MAX(CASE WHEN ap.TP_ACAO = 'A' THEN ap.STATUS END) AS STATUS_APROVACAO_AGENDA,
        MAX(CASE WHEN ap.TP_ACAO = 'C' THEN ap.STATUS END) AS STATUS_APROVACAO_CC,
        MAX(ap.DT_OPERACAO) AS DT_ULTIMA_APROVACAO
    FROM DBAMV.LOG_STATUS_APROVACAO_AVISO ap
    GROUP BY ap.CD_AVISO_CIRURGIA
)
SELECT
    -- Bloco 1: Status do Slot
    CASE
        WHEN a.TP_SITUACAO = 'R' THEN 'SLOT UTILIZADO'
        ELSE 'SLOT NAO UTILIZADO'
    END AS STATUS_SLOT,

    -- Bloco 2: Agenda (slot agendado)
    a.CD_AGE_CIR,
    a.DT_INICIO_AGE_CIR AS INICIO_AGENDADO,
    a.DT_FINAL_AGE_CIR AS FIM_AGENDADO,
    a.DURACAO_AGENDADA_MIN,
    a.TP_AGENDAMENTO,
    a.DS_SAL_CIR,
    a.DS_EQUIPE_MEDICA,

    -- Bloco 3: Aviso / Paciente
    a.CD_AVISO_CIRURGIA,
    a.NM_PACIENTE,
    a.TP_ATENDIMENTO,
    CASE a.TP_SITUACAO
        WHEN 'A' THEN 'Em Aviso'
        WHEN 'R' THEN 'Realizada'
        WHEN 'C' THEN 'Cancelada'
        WHEN 'G' THEN 'Agendada'
        WHEN 'T' THEN 'Checagem'
        WHEN 'P' THEN 'Pre-Agendamento'
        ELSE a.TP_SITUACAO
    END AS SITUACAO,
    CASE
        WHEN a.TP_CIRURGIAS = 'E' THEN 'Eletiva'
        WHEN a.TP_CIRURGIAS IN ('U','M') THEN 'Urgencia/Emergencia'
        ELSE 'Nao Classificada'
    END AS TIPO_CIRURGIA,
    a.SN_SUSPENSAO,

    -- Bloco 4: Procedimentos e Equipe
    a.PROCEDIMENTOS,
    a.ESPECIALIDADES,
    a.CIRURGIAO_PRINCIPAL,

    -- Bloco 5: Timestamps Reais
    a.DT_INICIO_ANESTESIA,
    a.DT_INICIO_CIRURGIA,
    a.DT_FIM_CIRURGIA,
    a.DT_FIM_ANESTESIA,
    a.DT_SAIDA_SAL_CIR,
    a.DT_INICIO_LIMPEZA,
    a.DT_FIM_LIMPEZA,

    -- Bloco 6: Performance - Agendado vs Real
    a.DURACAO_CIRURGIA_REAL_MIN,
    a.DURACAO_ANESTESIA_MIN,
    a.DURACAO_LIMPEZA_MIN,
    a.PERMANENCIA_SALA_MIN,
    CASE WHEN a.DURACAO_AGENDADA_MIN > 0 AND a.PERMANENCIA_SALA_MIN IS NOT NULL
         THEN a.PERMANENCIA_SALA_MIN - a.DURACAO_AGENDADA_MIN
    END AS DESVIO_TEMPO_MIN,

    -- Bloco 7: Cancelamento/Atraso
    a.DT_CANCELAMENTO,
    a.MOTIVO_CANCELAMENTO,
    a.TIPO_MOTIVO_CANCELAMENTO,
    a.MOTIVO_ATRASO,

    -- Bloco 8: Metricas por Sala
    COUNT(*) OVER (PARTITION BY a.DS_SAL_CIR) AS TOTAL_AGENDAMENTOS_SALA,
    SUM(CASE WHEN a.TP_SITUACAO = 'R' THEN 1 ELSE 0 END)
        OVER (PARTITION BY a.DS_SAL_CIR) AS REALIZADAS_SALA,
    SUM(CASE WHEN a.TP_SITUACAO = 'C' THEN 1 ELSE 0 END)
        OVER (PARTITION BY a.DS_SAL_CIR) AS CANCELADAS_SALA,
    ROUND(AVG(CASE WHEN a.TP_SITUACAO = 'R' THEN a.DURACAO_CIRURGIA_REAL_MIN END)
        OVER (PARTITION BY a.DS_SAL_CIR)) AS MEDIA_CIRURGIA_SALA_MIN,
    ROUND(AVG(CASE WHEN a.TP_SITUACAO = 'R' THEN a.PERMANENCIA_SALA_MIN END)
        OVER (PARTITION BY a.DS_SAL_CIR)) AS MEDIA_PERMANENCIA_SALA_MIN,

    -- Bloco 9: Metricas Globais
    COUNT(*) OVER () AS TOTAL_AGENDAMENTOS,
    SUM(CASE WHEN a.TP_SITUACAO = 'R' THEN 1 ELSE 0 END)
        OVER () AS TOTAL_REALIZADAS,
    SUM(CASE WHEN a.TP_SITUACAO = 'C' THEN 1 ELSE 0 END)
        OVER () AS TOTAL_CANCELADAS,

    -- Bloco 10: Historico de Mudancas
    COALESCE(le.QTD_MUDANCAS_STATUS, 0) AS QTD_MUDANCAS_STATUS,
    COALESCE(le.QTD_REVERSOES_GP, 0) AS QTD_REVERSOES_GP,
    CASE WHEN le.QTD_REVERSOES_GP > 0 THEN 'S' ELSE 'N' END AS SN_REVERTEU_PRE_AGENDAMENTO,
    le.HISTORICO_STATUS,
    le.DT_ULTIMA_MUDANCA,
    usr.NM_USUARIO AS USUARIO_ULTIMA_MUDANCA,
    COALESCE(lss.QTD_SUSPENSOES, 0) AS QTD_SUSPENSOES,
    lss.MOTIVO_ULTIMA_SUSPENSAO,
    COALESCE(la.QTD_REPROVACOES, 0) AS QTD_REPROVACOES,
    la.STATUS_APROVACAO_AGENDA,
    la.STATUS_APROVACAO_CC,

    -- Bloco 11: Metricas Globais de Alteracoes
    SUM(CASE WHEN le.QTD_REVERSOES_GP > 0 THEN 1 ELSE 0 END) OVER () AS TOTAL_COM_REVERSAO_GP,
    SUM(CASE WHEN lss.QTD_SUSPENSOES > 0 THEN 1 ELSE 0 END) OVER () AS TOTAL_COM_SUSPENSAO

FROM AGRUPADO a
LEFT JOIN LOG_EVOLUCAO le ON le.CD_AVISO_CIRURGIA = a.CD_AVISO_CIRURGIA
LEFT JOIN LOG_SUSPENSAO lss ON lss.CD_AVISO_CIRURGIA = a.CD_AVISO_CIRURGIA
LEFT JOIN LOG_APROVACAO la ON la.CD_AVISO_CIRURGIA = a.CD_AVISO_CIRURGIA
LEFT JOIN DBASGU.USUARIOS usr ON usr.CD_USUARIO = le.USUARIO_ULTIMA_MUDANCA
ORDER BY
    a.DT_INICIO_AGE_CIR,
    a.DS_SAL_CIR
