WITH params AS (
    SELECT
        TRUNC(ADD_MONTHS(SYSDATE, -10), 'MM') AS dh_inicio,
        SYSDATE AS dh_fim
    FROM DUAL
),  
-- CTE 1: Agrupa os prestadores (Principal e Auxiliares) para cada PROCEDIMENTO.
  PRESTADORES_POR_PROCEDIMENTO AS (
    SELECT
      pa.CD_CIRURGIA_AVISO,
      LISTAGG(CASE WHEN pa.SN_PRINCIPAL = 'S' THEN pa.NM_PRESTADOR END, '; ') WITHIN GROUP (ORDER BY pa.NM_PRESTADOR) AS CIRURGIAO_PRINCIPAL,
      LISTAGG(CASE WHEN pa.SN_PRINCIPAL != 'S' OR pa.SN_PRINCIPAL IS NULL THEN pa.NM_PRESTADOR END, '; ') WITHIN GROUP (ORDER BY pa.NM_PRESTADOR) AS CIRURGIOES_AUXILIARES
    FROM DBAMV.PRESTADOR_AVISO pa
    WHERE pa.CD_CIRURGIA_AVISO IS NOT NULL
    GROUP BY
      pa.CD_CIRURGIA_AVISO
  )

SELECT 
  ca.CD_AVISO_CIRURGIA,
  ca.CD_CIRURGIA_AVISO,
  ca.CD_CIRURGIA,
  cir.DS_CIRURGIA, 
  cir.CD_PROCEDimento_SIH,
  ppp.CIRURGIAO_PRINCIPAL,      -- << NOVO: Nome do Cirurgião Principal
  ppp.CIRURGIOES_AUXILIARES,    -- << NOVO: Nomes dos Cirurgiões Auxiliares
  ca.SN_PRINCIPAL,
  esp.DS_ESPECIALID, 
  ca.TP_CIRURGIA,
  va.DS_VIA_DE_ACESSO,
  gc.DS_GRUPO_CIRURGIA,
  sgc.DS_SUB_GRUPO_CIRURGIA, 
  ca.SN_REOP,
  ca.SN_ANTIMICROB_PROFILATICO,
  ca.TP_NATUREZA,
  ca.DS_LATERALIDADE
FROM 
  DBAMV.CIRURGIA_AVISO ca
  LEFT JOIN DBAMV.CIRURGIA cir ON ca.CD_CIRURGIA = cir.CD_CIRURGIA
  LEFT JOIN DBAMV.ESPECIALID esp ON ca.CD_ESPECIALID = esp.CD_ESPECIALID
  LEFT JOIN DBAMV.VIA_DE_ACESSO va ON ca.CD_VIA_DE_ACESSO = va.CD_VIA_DE_ACESSO
  LEFT JOIN DBAMV.GRUPO_CIRURGIA gc ON ca.CD_GRUPO_CIRURGIA = gc.CD_GRUPO_CIRURGIA
  LEFT JOIN DBAMV.SUB_GRUPO_CIRURGIA sgc ON ca.CD_SUB_GRUPO_CIRURGIA = sgc.CD_SUB_GRUPO_CIRURGIA
  LEFT JOIN PRESTADORES_POR_PROCEDIMENTO ppp ON ca.CD_CIRURGIA_AVISO = ppp.CD_CIRURGIA_AVISO -- << NOVO: Junção com a CTE de prestadores

WHERE ca.CD_AVISO_CIRURGIA IN (
  SELECT ac.CD_AVISO_CIRURGIA 
  FROM DBAMV.AVISO_CIRURGIA ac
  INNER JOIN DBAMV.ATENDIME atd ON ac.cd_atendimento = atd.cd_atendimento
  CROSS JOIN params p
  WHERE atd.cd_MULTI_EMPRESA = 40
    AND ac.DT_REALIZACAO BETWEEN p.dh_inicio AND p.dh_fim
    AND ac.TP_SITUACAO = 'R'
)
ORDER BY 
  ca.CD_AVISO_CIRURGIA,
  ca.CD_CIRURGIA_AVISO