-- Usamos uma CTE (WITH) para primeiro reunir todos os dados necessários
WITH BASE_DADOS AS (
    SELECT
        -- Colunas para o resultado final
        AC.CD_AVISO_CIRURGIA,
        AC.DT_AVISO_CIRURGIA,
        P.NM_PACIENTE,
        AC.TP_SITUACAO,
        A.TP_ATENDIMENTO,
        AC.VL_TEMPO_PREVISTO,
        AC.DT_REALIZACAO,
        AC.VL_TEMPO_DURACAO,
        AC.DS_OBS_AVISO,
        AC.SN_ALTERADO,
        AC.DT_PRE_AGENDAMENTO,
        AC.DT_AGENDAMENTO,
        AC.DT_CONFIRMACAO,
        AC.DT_CANCELAMENTO, -- !! 1. DATA DE CANCELAMENTO ADICIONADA AQUI !!
        AC.TP_CIRURGIAS,
        -- Colunas que podem ter múltiplos valores (para o LISTAGG)
        COALESCE(PSUS.CD_PROCEDIMENTO || ' - ' || PSUS.DS_PROCEDIMENTO, CIR.CD_CIRURGIA || ' - ' || CIR.DS_CIRURGIA) AS PROCEDIMENTO,
        ESP.DS_ESPECIALID,
        -- NOVAS COLUNAS COM AS DESCRIções DOS MOTIVOS
        MC_ATRASO.DS_MOT_CANC AS DS_MOTIVO_ATRASO,
        MC_CANC.DS_MOT_CANC AS DS_MOTIVO_CANCELAMENTO
    FROM
        AVISO_CIRURGIA AC
    INNER JOIN PACIENTE P         ON P.CD_PACIENTE = AC.CD_PACIENTE
    INNER JOIN ATENDIME A         ON A.CD_ATENDIMENTO = AC.CD_ATENDIMENTO
    INNER JOIN CIRURGIA_AVISO CA    ON CA.CD_AVISO_CIRURGIA = AC.CD_AVISO_CIRURGIA
    LEFT JOIN  CIRURGIA CIR       ON CA.CD_CIRURGIA = CIR.CD_CIRURGIA
    LEFT JOIN  PROCEDIMENTO_SUS PSUS ON CIR.CD_PROCEDIMENTO_SIH = PSUS.CD_PROCEDIMENTO
    LEFT JOIN  ESPECIALID ESP    ON ESP.CD_ESPECIALID = CA.CD_ESPECIALID
    LEFT JOIN  MOT_CANC MC_ATRASO  ON AC.CD_MOT_CANC_ATRASO = MC_ATRASO.CD_MOT_CANC
    LEFT JOIN  MOT_CANC MC_CANC    ON AC.CD_MOT_CANC = MC_CANC.CD_MOT_CANC
    WHERE
        A.CD_MULTI_EMPRESA = 40
    AND A.TP_ATENDIMENTO IN ('I','H','U')
    AND AC.DT_AVISO_CIRURGIA BETWEEN $pgmvDataIni$ AND $pgmvDataFim$
)
-- SELECT final que agrupa e organiza os resultados
SELECT
    -- Bloco 1: Identificadores Principais
    BD.CD_AVISO_CIRURGIA,
    BD.NM_PACIENTE,
    
    -- Bloco 2: Status, Classificação e Motivos
    CASE BD.TP_SITUACAO
        WHEN 'A' THEN 'Em aviso'
        WHEN 'R' THEN 'Realizada'
        WHEN 'C' THEN 'Cancelada'
        WHEN 'G' THEN 'Agendada'
        WHEN 'T' THEN 'Controle de checagem'
        WHEN 'P' THEN 'Pre-Agendamento'
        ELSE BD.TP_SITUACAO
    END AS SITUACAO,
    CASE
        WHEN BD.TP_CIRURGIAS = 'E' THEN 'Eletiva'
        WHEN BD.TP_CIRURGIAS IN ('U', 'M') THEN 'Urgência/Emergência'
        ELSE 'Não Classificada'
    END AS TIPO_CIRURGIA,
    BD.DS_MOTIVO_CANCELAMENTO,
    BD.DS_MOTIVO_ATRASO,
    
    -- Bloco 3: Listas Agrupadas
    LISTAGG(DISTINCT BD.PROCEDIMENTO, '; ') WITHIN GROUP (ORDER BY BD.PROCEDIMENTO) AS PROCEDIMENTOS_REALIZADOS,
    LISTAGG(DISTINCT BD.DS_ESPECIALID, '; ') WITHIN GROUP (ORDER BY BD.DS_ESPECIALID) AS ESPECIALIDADES,

    -- Bloco 4: Datas Importantes
    BD.DT_AVISO_CIRURGIA,
    BD.DT_PRE_AGENDAMENTO,
    BD.DT_AGENDAMENTO,
    BD.DT_REALIZACAO,
    BD.DT_CONFIRMACAO,
    BD.DT_CANCELAMENTO,
    
    -- Bloco 5: Detalhes Adicionais
    BD.TP_ATENDIMENTO,
    BD.VL_TEMPO_PREVISTO,
    BD.VL_TEMPO_DURACAO,
    BD.DS_OBS_AVISO,
    BD.SN_ALTERADO
FROM
    BASE_DADOS BD
GROUP BY
    BD.CD_AVISO_CIRURGIA,
    BD.NM_PACIENTE,
    BD.TP_SITUACAO,
    BD.TP_CIRURGIAS,
    BD.DS_MOTIVO_CANCELAMENTO,
    BD.DS_MOTIVO_ATRASO,
    BD.DT_AVISO_CIRURGIA,
    BD.DT_PRE_AGENDAMENTO,
    BD.DT_AGENDAMENTO,
    BD.DT_CONFIRMACAO,
    BD.DT_REALIZACAO,
    BD.DT_CANCELAMENTO, 
    BD.TP_ATENDIMENTO,
    BD.VL_TEMPO_PREVISTO,
    BD.VL_TEMPO_DURACAO,
    BD.DS_OBS_AVISO,
    BD.SN_ALTERADO
ORDER BY
    BD.NM_PACIENTE,
    BD.DT_AVISO_CIRURGIA