WITH params AS (
    SELECT
        TRUNC(ADD_MONTHS(SYSDATE, -10), 'MM') AS dh_inicio,
        SYSDATE AS dh_fim
    FROM DUAL
),

-- CTE 1: Base unificada, com a filtragem inicial AJUSTADA conforme sua solicitação.
 BASE_POR_AVISO AS (
    SELECT 
      -- Campos de AVISO_CIRURGIA
      ac.CD_AVISO_CIRURGIA, ac.TP_CIRURGIAS, ac.DT_AVISO_CIRURGIA, ac.DT_REALIZACAO, 
      ac.DT_INICIO_ANESTESIA, ac.DT_INICIO_CIRURGIA, ac.DT_FIM_CIRURGIA, 
      ac.DT_FIM_ANESTESIA, ac.DT_SAIDA_SAL_CIR, ac.DT_INICIO_LIMPEZA, ac.DT_FIM_LIMPEZA,
      -- Campos de ATENDIME
      atd.CD_ATENDIMENTO, atd.HR_ATENDIMENTO, atd.HR_ALTA, atd.SN_OBITO, atd.CD_MOT_ALT,
      -- Campos de PACIENTE
      pac.CD_PACIENTE, pac.NM_PACIENTE,
      -- Campos de MOT_ALT
      ma.DS_MOT_ALT
    FROM DBAMV.AVISO_CIRURGIA ac
    LEFT JOIN DBAMV.ATENDIME atd ON ac.CD_ATENDIMENTO = atd.CD_ATENDIMENTO
    LEFT JOIN DBAMV.PACIENTE pac ON atd.CD_PACIENTE = pac.CD_PACIENTE
    LEFT JOIN DBAMV.MOT_ALT ma ON atd.CD_MOT_ALT = ma.CD_MOT_ALT
    WHERE 
          -- REGRAS AJUSTADAS CONFORME SOLICITADO --
          atd.CD_MULTI_EMPRESA = 40
      AND atd.TP_ATENDIMENTO IN ('I', 'U', 'M', 'E', 'A')
      AND ac.TP_SITUACAO = 'R'
          ------------------------------------------
      AND ac.DT_REALIZACAO BETWEEN (SELECT dh_inicio FROM params) AND (SELECT dh_fim FROM params)
 ),

-- CTE 2: Usa a tabela MOV_CC_RPA para o cálculo de tempo de RPA (sem alteração).
 DADOS_RPA AS (
    SELECT
      CD_AVISO_CIRURGIA,
      (MAX(DT_SAIDA_RPA) - MIN(DT_ENTRADA_RPA)) * 24 AS TEMPO_RPA_HORAS
    FROM DBAMV.MOV_CC_RPA
    WHERE DT_ENTRADA_RPA IS NOT NULL AND DT_SAIDA_RPA IS NOT NULL
    GROUP BY CD_AVISO_CIRURGIA
 ),

-- CTE 3: Calcula a flag de reoperação de forma segura (sem alteração).
 FLAG_REOPERACAO_CTE AS (
    SELECT
      CD_AVISO_CIRURGIA,
      CASE 
        WHEN (DT_INICIO_CIRURGIA - LAG(DT_INICIO_CIRURGIA, 1) OVER (PARTITION BY CD_PACIENTE ORDER BY DT_INICIO_CIRURGIA)) <= 30 
        THEN 'SIM' 
        ELSE 'NAO' 
      END AS FLAG_REOPERACAO_30D
    FROM (
      SELECT 
        ac.CD_AVISO_CIRURGIA, 
        ac.DT_INICIO_CIRURGIA, 
        atd.CD_PACIENTE
      FROM DBAMV.AVISO_CIRURGIA ac
      LEFT JOIN DBAMV.ATENDIME atd ON ac.CD_ATENDIMENTO = atd.CD_ATENDIMENTO
      WHERE ac.TP_SITUACAO = 'R'
    )
 ),

-- CTE 4: Constrói a base da jornada, agora muito mais simples.
 DADOS_BASE_CIRURGIA AS (
    SELECT
      bpa.*,
      rpa.TEMPO_RPA_HORAS,
      reop.FLAG_REOPERACAO_30D,
      p.dh_fim
    FROM BASE_POR_AVISO bpa
    CROSS JOIN params p
    LEFT JOIN DADOS_RPA rpa ON bpa.CD_AVISO_CIRURGIA = rpa.CD_AVISO_CIRURGIA
    LEFT JOIN FLAG_REOPERACAO_CTE reop ON bpa.CD_AVISO_CIRURGIA = reop.CD_AVISO_CIRURGIA
 ),

-- CTE 5: Realiza os cálculos de janela (sem alteração).
 CALCULOS_JORNADA AS (
    SELECT
      b.*,
      DENSE_RANK() OVER (PARTITION BY b.CD_ATENDIMENTO ORDER BY b.DT_INICIO_CIRURGIA) AS NR_CIRURGIA_NA_INTERNACAO,
      DENSE_RANK() OVER (PARTITION BY b.CD_PACIENTE ORDER BY b.DT_INICIO_CIRURGIA) AS NR_CIRURGIA_DO_PACIENTE,
      COUNT(b.CD_AVISO_CIRURGIA) OVER (PARTITION BY b.CD_ATENDIMENTO) AS TOTAL_CIRURGIAS_NA_INTERNACAO,
      MIN(b.DT_INICIO_CIRURGIA) OVER (PARTITION BY b.CD_ATENDIMENTO) AS DT_PRIMEIRA_CIRURGIA_NO_ATEND,
      MAX(b.DT_INICIO_CIRURGIA) OVER (PARTITION BY b.CD_ATENDIMENTO) AS DT_ULTIMA_CIRURGIA_NO_ATEND,
      CASE WHEN b.SN_OBITO = 'S' AND (TRUNC(b.HR_ALTA) - TRUNC(b.DT_INICIO_CIRURGIA)) BETWEEN 0 AND 7 THEN 'SIM' ELSE 'NAO' END AS FLAG_MORTALIDADE_7D
    FROM DADOS_BASE_CIRURGIA b
 )

-- Query Final: Seleciona e formata os dados (sem alteração).
SELECT
 -- Bloco 1: Paciente
 c.CD_PACIENTE, c.NM_PACIENTE,
 -- Bloco 2: Internação
 c.CD_ATENDIMENTO, c.HR_ATENDIMENTO AS DATA_INTERNACAO, c.HR_ALTA AS DATA_ALTA, c.DS_MOT_ALT AS MOTIVO_ALTA,
 -- Bloco 3: Evento Cirúrgico
 c.CD_AVISO_CIRURGIA, c.DT_AVISO_CIRURGIA, 
 c.NR_CIRURGIA_NA_INTERNACAO AS NR_PROCED_NA_INTERNACAO,
 CASE WHEN c.NR_CIRURGIA_DO_PACIENTE > c.NR_CIRURGIA_NA_INTERNACAO THEN 'SIM' ELSE 'NAO' END AS FLAG_PROCEDIMENTO_PREVIO,
 c.FLAG_REOPERACAO_30D,
 CASE
   WHEN c.TP_CIRURGIAS = 'E' THEN 'Eletiva'
   ELSE 'Urgência'
 END AS CLASSIFICACAO_CIRURGIA,
 c.FLAG_MORTALIDADE_7D,
 
 -- Bloco 4: Métricas de Tempo e Duração
 CAST(ROUND(c.TEMPO_RPA_HORAS, 2) AS NUMBER(10,2)) AS TEMPO_RPA_HORAS,
 CAST(ROUND(NVL(c.HR_ALTA, c.dh_fim) - c.HR_ATENDIMENTO, 2) AS NUMBER(10,2)) AS TEMPO_TOTAL_INTERNACAO_DIAS,
 CAST(CASE 
   WHEN c.NR_CIRURGIA_NA_INTERNACAO = 1 AND c.TP_CIRURGIAS IN ('E', 'X') 
   THEN ROUND(c.DT_INICIO_CIRURGIA - c.HR_ATENDIMENTO, 2) 
   ELSE NULL 
 END AS NUMBER(10,2)) AS TEMPO_PRE_CIRURGICO_DIAS,
 CAST(CASE 
   WHEN c.NR_CIRURGIA_DO_PACiente = 1 AND c.HR_ALTA IS NOT NULL
   THEN ROUND(c.HR_ALTA - c.DT_PRIMEIRA_CIRURGIA_NO_ATEND, 2) 
   ELSE NULL 
 END AS NUMBER(10,2)) AS DIAS_PRIMEIRA_CIR_ATE_ALTA,
 CAST(CASE 
   WHEN c.NR_CIRURGIA_DO_PACIENTE >= 2 AND c.NR_CIRURGIA_NA_INTERNACAO = c.TOTAL_CIRURGIAS_NA_INTERNACAO AND c.HR_ALTA IS NOT NULL
   THEN ROUND(c.HR_ALTA - c.DT_ULTIMA_CIRURGIA_NO_ATEND, 2) 
   ELSE NULL 
 END AS NUMBER(10,2)) AS DIAS_ULTIMA_CIR_ATE_ALTA,
 CAST(ROUND((c.DT_SAIDA_SAL_CIR - c.DT_INICIO_CIRURGIA) * 24 * 60) AS NUMBER(10,2)) AS TEMPO_PERMANENCIA_SALA_MINUTOS,
 CAST(ROUND((c.DT_SAIDA_SAL_CIR - c.DT_FIM_CIRURGIA) * 24 * 60) AS NUMBER(10,2)) AS TEMPO_FIM_CIR_SAIDA_SALA_MINUTOS,
 
 -- Bloco 5: Timestamps Detalhados do Processo Cirúrgico
 c.DT_REALIZACAO,
 c.DT_INICIO_ANESTESIA,
 c.DT_INICIO_CIRURGIA,
 c.DT_FIM_CIRURGIA,
 c.DT_FIM_ANESTESIA,
 c.DT_SAIDA_SAL_CIR,
 c.DT_INICIO_LIMPEZA,
 c.DT_FIM_LIMPEZA,
 
 -- Bloco 6: Métrica Final
 CAST(ROUND((c.DT_FIM_LIMPEZA - c.DT_REALIZACAO) * 24 * 60) AS NUMBER(10,2)) AS TEMPO_TOTAL_SALA_MINUTOS

FROM CALCULOS_JORNADA c
ORDER BY
 c.CD_PACIENTE,
 c.DT_INICIO_CIRURGIA